import { Project } from "@/types/projects";

export const projects: Project[] = [
  {
    id: "advisor-onboarding-system-transformation",
    slug: "advisor-onboarding-system-transformation",
    title: "Advisor Onboarding System Transformation",
    shortTitle: "Advisor Onboarding",
    category: "Project Management",
    projectType: "Onboarding / Implementation",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2023-03",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Transformed manual advisor onboarding from email and PDF setup into an automated, self-serve SaaS workflow.",
    shortResumeVersion:
      "Led the shift from manual advisor onboarding to a self-serve SaaS workflow spanning signup, plan purchase, activation, and dashboard access.",
    longResumeVersion:
      "Directed onboarding structure, user guidance, documentation, and workflow refinement for Finliti's advisor setup experience, replacing fragmented email and PDF processes with a more scalable self-serve flow that reduced manual coordination and improved readiness for firm pilots.",
    context:
      "Advisor onboarding previously relied on email threads, PDFs, and manual survey distribution. The experience lacked system visibility, created avoidable friction, and made it harder to scale onboarding across multiple advisors and firms.",
    objective:
      "Reduce onboarding friction and create a more scalable, professional advisor setup experience.",
    ownership: [
      "Onboarding flow structure",
      "User guidance and product copy",
      "Documentation systems",
      "Experience design",
      "Workflow refinement",
    ],
    deliverables: [
      "Simplified signup page",
      "Stripe plan purchase flow",
      "Automated activation logic",
      "Dashboard access setup",
      "Survey workflow coordination",
      "Demo bypass system for pilot usage",
    ],
    collaborators: ["CEO", "CTO", "Software developer"],
    skills: [
      "Onboarding design",
      "Workflow design",
      "Implementation support",
      "Stakeholder coordination",
      "Process improvement",
      "Product operations",
    ],
    tools: ["Next.js product interface", "Stripe", "Internal dashboards", "Survey tooling"],
    outcomes: [
      "Reduced manual onboarding steps and handoffs",
      "Created a clearer advisor setup path across signup, payment, and activation",
      "Improved scalability for firm pilots and repeatable onboarding",
    ],
    metrics: [
      { label: "Advisors onboarded", value: "~10" },
      { label: "Firms supported", value: "~4" },
      { label: "Workflow shift", value: "Manual to self-serve" },
    ],
    tags: [
      "implementation",
      "customer onboarding",
      "SaaS deployment",
      "workflow automation",
      "stakeholder management",
    ],
    featured: true,
    industry: "Fintech / WealthTech",
    audience: "Financial advisors and advisory firms",
    scopeLevel: "External / Pilot / B2B SaaS",
    relatedProjects: [
      "advisor-dashboard-platform-expansion",
      "enterprise-product-rollout-early-client-growth",
    ],
  },
  {
    id: "advisor-dashboard-platform-expansion",
    slug: "advisor-dashboard-platform-expansion",
    title: "Advisor Dashboard & Platform Expansion",
    shortTitle: "Platform Expansion",
    category: "Project Management",
    projectType: "Product Build / Dashboard / UX",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2023-03",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Helped evolve the platform from a narrow survey-report workflow into a broader advisor dashboard with integrated tools and clearer product structure.",
    shortResumeVersion:
      "Structured an expanding advisor platform into a more cohesive dashboard experience spanning insights, profiles, portfolio tools, and communications features.",
    longResumeVersion:
      "Owned product structuring, workflow clarity, and dashboard organization as Finliti expanded beyond standalone reports into a more unified advisor workspace. Shaped how new tools fit together so the platform remained understandable as features accumulated.",
    context:
      "The early product experience was fragmented and centered on isolated outputs rather than a centralized product environment. As new capabilities were introduced, the platform needed stronger information architecture and clearer user-facing organization.",
    objective:
      "Build a centralized advisor workspace where multiple tools and insights live together in a coherent product experience.",
    ownership: [
      "Product structuring",
      "Experience clarity",
      "Dashboard organization",
      "Content logic",
      "User-facing workflow design",
    ],
    deliverables: [
      "Integrated survey visibility",
      "Client profile access structure",
      "Behavioral insights display",
      "Portfolio tools organization",
      "Newsletter generation touchpoints",
      "AI and voice agent workflow touchpoints",
      "Market alert organization",
    ],
    collaborators: ["CEO", "CTO", "Software developer"],
    skills: [
      "UX thinking",
      "Information architecture",
      "Product design",
      "Feature organization",
      "Cross-functional collaboration",
    ],
    tools: ["Product dashboard", "Survey outputs", "Portfolio tools", "AI workflow concepts"],
    outcomes: [
      "Created a more cohesive advisor-facing product structure",
      "Improved usability as the feature set expanded",
      "Made the platform easier to explain and navigate for advisors",
    ],
    metrics: [
      { label: "Core focus", value: "Dashboard cohesion" },
      { label: "Feature scope", value: "Multi-tool advisor workspace" },
      { label: "State change", value: "Fragmented to unified" },
    ],
    tags: [
      "dashboard development",
      "product operations",
      "UX design",
      "feature rollout",
      "product enhancement",
    ],
    featured: true,
    industry: "Fintech / WealthTech",
    audience: "Financial advisors",
    scopeLevel: "External / B2B SaaS",
    relatedProjects: [
      "market-alerts-portfolio-signal-system",
      "crm-behavioral-profile-integration",
    ],
  },
  {
    id: "crm-behavioral-profile-integration",
    slug: "crm-behavioral-profile-integration",
    title: "CRM Behavioral Profile Integration",
    shortTitle: "CRM Integration",
    category: "Project Management",
    projectType: "Systems Integration / CRM / Data Workflow",
    company: "Finliti",
    client: "Wealthbox-related integration work",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2025-01",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Supported export and integration of behavioral profile data into CRM workflows so advisors could use personality insights in daily practice.",
    shortResumeVersion:
      "Defined workflow and data framing for CRM integration work that made behavioral profile data more usable inside advisor systems.",
    longResumeVersion:
      "Supported the practical integration of behavioral profile data into CRM-adjacent workflows by shaping export structure, clarifying use cases, and helping align profile information with advisor action inside day-to-day systems.",
    context:
      "Behavioral insights existed within the product, but they were not deeply embedded in the CRM environments advisors relied on to manage client relationships and workflows.",
    objective:
      "Make client personality profile data accessible within CRM environments and connected to advisor action.",
    ownership: [
      "Workflow definition",
      "Behavioral data framing",
      "Integration logic support",
      "Communication of advisor use cases",
    ],
    deliverables: [
      "Profile data export structure",
      "Internal CRM and Pulse workflow connections",
      "Alignment of investor profile data with advisor tools",
    ],
    collaborators: ["CEO", "CTO", "Software developer"],
    skills: [
      "Systems thinking",
      "CRM workflow design",
      "Data mapping support",
      "Product implementation",
      "Stakeholder communication",
    ],
    tools: ["CRM exports", "Profile data structures", "Internal workflow docs"],
    outcomes: [
      "Advanced the practical use of behavioral data in advisor workflows",
      "Improved readiness for CRM-connected delivery",
      "Created clearer connections between insight generation and action",
    ],
    metrics: [
      { label: "Integration focus", value: "Behavioral profile data" },
      { label: "Primary environment", value: "Advisor CRM workflows" },
      { label: "Status", value: "Active buildout" },
    ],
    tags: [
      "CRM integration",
      "data workflows",
      "systems integration",
      "implementation support",
      "cross-functional collaboration",
    ],
    featured: true,
    industry: "Fintech / WealthTech",
    audience: "Financial advisors using CRM systems",
    scopeLevel: "External / B2B / Integration",
    relatedProjects: [
      "advisor-dashboard-platform-expansion",
      "market-alerts-portfolio-signal-system",
    ],
  },
  {
    id: "market-alerts-portfolio-signal-system",
    slug: "market-alerts-portfolio-signal-system",
    title: "Market Alerts & Portfolio Signal System",
    shortTitle: "Market Alerts",
    category: "Project Management",
    projectType: "Product Feature / Alerts / Portfolio Workflow",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2025-01",
    timelineEnd: "Present",
    status: "Prototype",
    oneLineSummary:
      "Helped shape a market alert workflow that links portfolios, asset shelves, and investor profile logic to more actionable advisor insights.",
    shortResumeVersion:
      "Framed a market alert workflow connecting portfolio data, investor profiles, and user-facing insight logic to extend product value beyond static reporting.",
    longResumeVersion:
      "Defined feature logic and user-facing structure for an alerts system that uses uploaded portfolio data and investor profile context to surface more relevant signals, helping move the platform toward ongoing advisor utility rather than one-time outputs.",
    context:
      "Advisors needed more ongoing value from the platform than static reports alone. The product needed a clearer insight layer tying portfolio context and investor profile logic into regular usage.",
    objective:
      "Create an insight layer that links portfolios, market movement, and investor profile context.",
    ownership: [
      "Feature framing",
      "Workflow clarity",
      "User value articulation",
      "Interface logic support",
    ],
    deliverables: [
      "Alert concept organization",
      "Portfolio shelf usage logic",
      "Profile-based signal categorization",
      "User-facing structure for alerts and insights",
    ],
    collaborators: ["CEO", "CTO", "Software developer"],
    skills: [
      "Product strategy",
      "Feature planning",
      "Workflow design",
      "Information architecture",
    ],
    tools: ["Portfolio data imports", "Alert models", "Product workflow docs"],
    outcomes: [
      "Contributed to the platform's expansion into an ongoing advisor utility system",
      "Clarified how alerts connect to user value and platform logic",
      "Supported feature readiness for future rollout",
    ],
    metrics: [
      { label: "Feature stage", value: "Prototype / active shaping" },
      { label: "Core inputs", value: "Portfolio data + profile logic" },
      { label: "Value shift", value: "Static reports to ongoing insights" },
    ],
    tags: [
      "feature implementation",
      "alerts workflow",
      "portfolio tools",
      "product planning",
      "user experience",
    ],
    featured: false,
    industry: "Fintech / WealthTech",
    audience: "Financial advisors managing portfolios",
    scopeLevel: "External / Feature prototype",
    relatedProjects: [
      "advisor-dashboard-platform-expansion",
      "crm-behavioral-profile-integration",
    ],
  },
  {
    id: "lifecycle-email-engagement-system",
    slug: "lifecycle-email-engagement-system",
    title: "Lifecycle Email & Engagement System",
    shortTitle: "Lifecycle Email System",
    category: "Project Management",
    projectType: "Communications / Lifecycle / Engagement",
    company: "Finliti",
    role: "Product & Content Lead / Content Lead",
    location: "Toronto, ON",
    timelineStart: "2021-01",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Designed lifecycle emails and newsletters that improved engagement while supporting onboarding, education, and retention.",
    shortResumeVersion:
      "Built lifecycle email and newsletter systems that strengthened user education, onboarding continuity, and product engagement.",
    longResumeVersion:
      "Owned messaging strategy, content design, and lifecycle communication structure across advisor-facing journeys, producing email sequences and newsletters that improved clarity across touchpoints and helped sustain product engagement over time.",
    context:
      "Product adoption and user education required stronger communication structure so onboarding and ongoing engagement were not dependent on ad hoc outreach.",
    objective:
      "Improve clarity, engagement, and continuity across user touchpoints.",
    ownership: [
      "Messaging strategy",
      "Content design",
      "Email structure",
      "Ongoing communications",
    ],
    deliverables: [
      "Lifecycle email sequences",
      "Newsletters",
      "Advisor-facing communications",
      "Content systems tied to the user journey",
    ],
    collaborators: ["CEO", "Product stakeholders"],
    skills: [
      "Lifecycle marketing",
      "User communication",
      "Content strategy",
      "Onboarding support",
      "Engagement design",
    ],
    tools: ["Email platforms", "Newsletter workflows", "Messaging frameworks"],
    outcomes: [
      "Improved continuity across onboarding and retention touchpoints",
      "Helped maintain steady product engagement",
      "Created a reusable communications system rather than one-off sends",
    ],
    metrics: [
      { label: "Approx. open rate", value: "42%" },
      { label: "Primary goal", value: "Engagement + education" },
      { label: "Timeline", value: "2021 to present" },
    ],
    tags: [
      "email campaigns",
      "lifecycle communication",
      "customer engagement",
      "onboarding communications",
      "retention support",
    ],
    featured: false,
    industry: "Fintech / WealthTech",
    audience: "Advisors and product users",
    scopeLevel: "External / B2B and B2C communications",
    relatedProjects: [
      "advisor-onboarding-system-transformation",
      "b2c-discovery-survey-funnel",
    ],
  },
  {
    id: "b2c-discovery-survey-funnel",
    slug: "b2c-discovery-survey-funnel",
    title: "B2C Discovery Survey Funnel",
    shortTitle: "Discovery Funnel",
    category: "Project Management",
    projectType: "Funnel / Product Experience / User Acquisition",
    company: "Finliti",
    role: "Content Lead / Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2021-01",
    timelineEnd: "Present",
    status: "Launched",
    oneLineSummary:
      "Supported a discovery survey experience that drove more than 1,000 completions and fed product insight generation.",
    shortResumeVersion:
      "Shaped survey-facing content and product messaging for a B2C discovery funnel that generated 1,000+ completed surveys.",
    longResumeVersion:
      "Supported a scalable entry point into Finliti's behavioral finance experience by improving survey-facing content, report framing, and messaging clarity, helping turn the discovery flow into both an acquisition mechanism and a source of product insight.",
    context:
      "Finliti needed an accessible, compelling front door for users to discover behavioral finance profiles and enter the product ecosystem without high-touch guidance.",
    objective:
      "Build an accessible B2C experience that supports discovery and conversion.",
    ownership: [
      "Survey-facing content",
      "Experience clarity",
      "Report framing",
      "Product messaging",
    ],
    deliverables: [
      "Survey content refinement",
      "Discovery flow messaging",
      "Report framing improvements",
      "User journey support",
    ],
    collaborators: ["CEO", "Product stakeholders", "Software developer"],
    skills: [
      "User journey design",
      "Content strategy",
      "Conversion support",
      "Product messaging",
    ],
    tools: ["Survey platform", "Product reports", "Lifecycle messaging"],
    outcomes: [
      "Contributed to more than 1,000 completed discovery surveys",
      "Created a stronger acquisition and education entry point",
      "Improved clarity around how users engage with behavioral profile outputs",
    ],
    metrics: [
      { label: "Survey completions", value: "1,000+" },
      { label: "Primary use", value: "Discovery + conversion" },
      { label: "Launch state", value: "Active" },
    ],
    tags: [
      "funnel optimization",
      "user journey",
      "survey experience",
      "acquisition support",
      "customer engagement",
    ],
    featured: false,
    industry: "Fintech / WealthTech",
    audience: "Prospective retail users",
    scopeLevel: "External / B2C",
    relatedProjects: ["lifecycle-email-engagement-system"],
  },
  {
    id: "enterprise-product-rollout-early-client-growth",
    slug: "enterprise-product-rollout-early-client-growth",
    title: "Enterprise Product Rollout & Early Client Growth",
    shortTitle: "Enterprise Rollout",
    category: "Project Management",
    projectType: "Product Rollout / Early-Stage Growth / Client Delivery",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2023-01",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Helped move Finliti from an early startup stage with no revenue into a revenue-generating platform with advisors and enterprise firms on annual plans.",
    shortResumeVersion:
      "Supported product readiness, onboarding, and delivery as Finliti moved from pre-revenue experimentation to active advisor and enterprise relationships.",
    longResumeVersion:
      "Worked across product presentation, onboarding readiness, and rollout support during Finliti's transition from early-stage experimentation to commercial traction, helping strengthen the credibility and delivery structure needed for early client growth.",
    context:
      "The business was moving from pre-seed experimentation toward active commercial traction, which required a more credible product experience, stronger delivery readiness, and more structured client-facing execution.",
    objective:
      "Support product readiness, delivery, onboarding, and credibility for early clients.",
    ownership: [
      "Product presentation",
      "Onboarding readiness",
      "User-facing clarity",
      "Rollout support",
    ],
    deliverables: [
      "Client-facing product framing",
      "Rollout support materials",
      "Onboarding readiness improvements",
      "Execution support for early clients",
    ],
    collaborators: ["CEO", "CTO", "Software developer", "Advisors", "Enterprise firms"],
    skills: [
      "Startup operations",
      "Product rollout",
      "Implementation readiness",
      "Cross-functional execution",
      "Stakeholder support",
    ],
    tools: ["Client demos", "Product workflows", "Onboarding systems", "Internal documentation"],
    outcomes: [
      "Supported growth from zero clients and revenue to active advisor use",
      "Helped position the platform for enterprise relationships and annual plans",
      "Improved readiness for real client delivery in a startup environment",
    ],
    metrics: [
      { label: "Revenue stage", value: "Zero to active" },
      { label: "Client mix", value: "Advisors + enterprise firms" },
      { label: "Commercial phase", value: "Early traction" },
    ],
    tags: [
      "product rollout",
      "SaaS implementation",
      "early-stage growth",
      "client onboarding",
      "project coordination",
    ],
    featured: true,
    industry: "Fintech / WealthTech",
    audience: "Advisory firms and enterprise partners",
    scopeLevel: "External / Enterprise / B2B",
    relatedProjects: [
      "advisor-onboarding-system-transformation",
      "rbc-finsec-incubator-participation",
    ],
  },
  {
    id: "intern-coordination-feature-support",
    slug: "intern-coordination-feature-support",
    title: "Intern Coordination & Feature Support",
    shortTitle: "Intern Coordination",
    category: "Project Management",
    projectType: "Team Coordination / Delivery Support",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2024-01",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Coordinated intern contributions across product-related workstreams and feature support in a fast-moving startup environment.",
    shortResumeVersion:
      "Directed intern support across evolving product priorities, balancing coordination, review, and delivery support.",
    longResumeVersion:
      "Managed flexible resourcing across startup product workstreams by coordinating intern contributions, reviewing work, and directing effort toward the highest-value priorities as needs shifted.",
    context:
      "Startup work required adaptable support across changing priorities, and intern contributions needed guidance to align with current product goals and team bandwidth.",
    objective:
      "Direct available resources toward features and initiatives with the highest value.",
    ownership: [
      "Guidance",
      "Review",
      "Coordination",
      "Team communication",
    ],
    deliverables: [
      "Task direction across workstreams",
      "Review and feedback loops",
      "Priority alignment",
      "Cross-team coordination support",
    ],
    collaborators: ["Interns", "CEO", "CTO", "Software developer"],
    skills: [
      "Coordination",
      "Prioritization",
      "Delegation",
      "Review",
      "Communication",
    ],
    tools: ["Shared task lists", "Product briefs", "Async communication"],
    outcomes: [
      "Improved alignment of intern effort with active product priorities",
      "Provided lightweight team management in a lean environment",
      "Reduced drift on feature support work",
    ],
    metrics: [
      { label: "Team model", value: "Lean startup + interns" },
      { label: "Primary value", value: "Priority alignment" },
      { label: "Work mode", value: "Flexible delivery support" },
    ],
    tags: [
      "team coordination",
      "cross-functional collaboration",
      "project support",
      "task management",
    ],
    featured: false,
    industry: "Fintech / WealthTech",
    audience: "Internal product team",
    scopeLevel: "Internal",
    relatedProjects: ["enterprise-product-rollout-early-client-growth"],
  },
  {
    id: "rbc-finsec-incubator-participation",
    slug: "rbc-finsec-incubator-participation",
    title: "RBC FinSec Incubator Participation",
    shortTitle: "RBC FinSec",
    category: "Project Management",
    projectType: "Strategic Stakeholder Engagement / Ecosystem Exposure",
    company: "Finliti",
    role: "Product & Content Lead / Company Representative",
    location: "Toronto, ON",
    timelineStart: "2023-01",
    timelineEnd: "2023-12",
    status: "Strategic",
    oneLineSummary:
      "Participated in the RBC FinSec incubator and contributed to conversations with Canadian fintech and banking stakeholders.",
    shortResumeVersion:
      "Represented Finliti in RBC FinSec incubator conversations and supported stakeholder-facing product positioning during a growth stage.",
    longResumeVersion:
      "Contributed to Finliti's visibility and strategic positioning through incubator participation and stakeholder conversations across the Canadian fintech and banking ecosystem, supporting credibility during an early growth phase.",
    context:
      "Finliti was working to build market credibility and visibility while refining the product and strengthening its position in the fintech ecosystem.",
    objective:
      "Engage industry stakeholders and strengthen strategic positioning.",
    ownership: [
      "Communication",
      "Product positioning support",
      "Stakeholder-facing representation",
    ],
    deliverables: [
      "Incubator participation",
      "Stakeholder conversations",
      "Product positioning support",
      "Startup representation",
    ],
    collaborators: ["CEO", "External fintech stakeholders", "Banking stakeholders"],
    skills: [
      "Communication",
      "Product positioning",
      "Stakeholder engagement",
      "Startup representation",
    ],
    tools: ["Pitch materials", "Product narrative", "Stakeholder meetings"],
    outcomes: [
      "Strengthened exposure within the fintech ecosystem",
      "Supported external credibility during a growth stage",
      "Helped connect product work to strategic conversations",
    ],
    metrics: [
      { label: "Program", value: "RBC FinSec incubator" },
      { label: "Focus", value: "Strategic positioning" },
      { label: "Timeline", value: "2023" },
    ],
    tags: [
      "stakeholder engagement",
      "fintech",
      "enterprise readiness",
      "external collaboration",
    ],
    featured: false,
    industry: "Fintech / Banking",
    audience: "Industry stakeholders and ecosystem partners",
    scopeLevel: "External / Strategic",
    relatedProjects: ["enterprise-product-rollout-early-client-growth"],
  },
];
