import { Project } from "@/types/projects";

export const projects: Project[] = [
  {
    id: "advisor-onboarding-system-transformation",
    slug: "advisor-onboarding-system-transformation",
    title: "Advisor Onboarding System Transformation",
    shortTitle: "Advisor Onboarding",
    category: "Project Management",
    projectType: "Onboarding / Implementation",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2023-03",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Transformed advisor onboarding from a manual, email-based process into a fully automated SaaS onboarding system.",
    shortResumeVersion:
      "Transformed advisor onboarding from a manual, email-based process into a fully automated SaaS onboarding system.",
    longResumeVersion:
      "Owned onboarding flow design, user experience structure, documentation, and system flow as Finliti moved advisor onboarding from email signups and manual survey distribution into a centralized self-serve SaaS experience.",
    context:
      "Onboarding was previously handled through email signups, PDF reports, and manual survey distribution with no centralized system or visibility.",
    objective:
      "Create a scalable, low-friction onboarding experience for advisors and firms.",
    ownership: [
      "Onboarding flow design",
      "User experience structure",
      "Documentation and guidance",
      "Onboarding logic and system flow",
    ],
    deliverables: [
      "Designed simplified signup flow",
      "Implemented Stripe-based plan purchase system",
      "Structured automated onboarding activation",
      "Created dashboard-based onboarding experience",
      "Built survey distribution workflow for advisor clients",
      "Introduced demo bypass system for pilot environments",
    ],
    collaborators: ["CEO", "CTO", "1 software developer"],
    skills: [
      "Onboarding design",
      "Implementation",
      "Workflow design",
      "SaaS operations",
      "Stakeholder coordination",
      "Product operations",
    ],
    tools: ["Stripe", "Advisor dashboard", "Survey workflow"],
    outcomes: [
      "Onboarded ~10 advisors across ~4 firms",
      "Reduced reliance on manual onboarding processes",
      "Enabled self-serve onboarding vs assisted setup",
      "Improved scalability of advisor acquisition",
    ],
    metrics: [
      { label: "Advisors", value: "~10" },
      { label: "Firms", value: "~4" },
      { label: "Model", value: "Self-serve onboarding" },
    ],
    tags: [
      "Onboarding / Implementation",
      "Advisor onboarding",
      "Stripe",
      "Workflow design",
      "Product operations",
    ],
    featured: true,
    industry: "Fintech / WealthTech",
    audience: "Advisors and advisory firms",
    scopeLevel: "External / B2B SaaS",
    coverImage: {
      src: "/project-images/pm/advisor-onboarding-flow.png",
      alt: "Finliti advisor onboarding flow diagram.",
      fit: "contain",
      position: "center",
    },
    relatedProjects: [
      "advisor-dashboard-platform-expansion",
      "enterprise-rollout-early-client-growth",
    ],
  },
  {
    id: "advisor-dashboard-platform-expansion",
    slug: "advisor-dashboard-platform-expansion",
    title: "Advisor Dashboard & Platform Expansion",
    shortTitle: "Dashboard Expansion",
    category: "Project Management",
    projectType: "Product Build / Dashboard / UX",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2023-03",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Expanded product from a simple survey/report tool into a multi-feature advisor platform with a unified dashboard.",
    shortResumeVersion:
      "Expanded the product from a simple survey/report tool into a multi-feature advisor platform with a unified dashboard.",
    longResumeVersion:
      "Owned dashboard structure, product organization, and user-facing feature integration as Finliti evolved from a fragmented report tool into a centralized advisor workspace.",
    context:
      "Initial product experience was fragmented and centered on standalone reports without a centralized system.",
    objective:
      "Create a cohesive advisor workspace where all tools and insights live in one system.",
    ownership: [
      "Dashboard structure and logic",
      "Product organization and clarity",
      "User-facing feature integration",
      "Experience design",
    ],
    deliverables: [
      "Unified advisor dashboard",
      "Client profile visibility system",
      "Survey result integration",
      "Portfolio builder integration",
      "Backtesting tools integration",
      "Newsletter generator integration",
      "AI voice/audio agent integration",
      "Structured feature navigation",
    ],
    collaborators: ["CEO", "CTO", "Software developer"],
    skills: [
      "UX design",
      "Product structuring",
      "Information architecture",
      "Feature integration",
      "Cross-functional collaboration",
    ],
    tools: [
      "Advisor dashboard",
      "Portfolio builder",
      "Backtesting tools",
      "Newsletter generator",
      "AI voice/audio agent",
    ],
    outcomes: [
      "Transformed product into a centralized SaaS platform",
      "Improved usability and feature discoverability",
      "Enabled expansion into ongoing advisor workflows",
    ],
    metrics: [
      { label: "Product state", value: "Centralized platform" },
      { label: "Primary gain", value: "Usability" },
      { label: "Mode", value: "Multi-feature dashboard" },
    ],
    tags: [
      "Product Build / Dashboard / UX",
      "Dashboard",
      "Information architecture",
      "Feature integration",
      "Advisor platform",
    ],
    featured: true,
    industry: "Fintech / WealthTech",
    audience: "Advisors",
    scopeLevel: "External / B2B SaaS",
    coverImage: {
      src: "/project-images/pm/dashboard-platform.png",
      alt: "Finliti advisor dashboard interface.",
    },
    relatedProjects: [
      "market-alerts-portfolio-signal-system",
      "crm-behavioral-profile-integration",
    ],
  },
  {
    id: "crm-behavioral-profile-integration",
    slug: "crm-behavioral-profile-integration",
    title: "CRM Behavioral Profile Integration",
    shortTitle: "CRM Integration",
    category: "Project Management",
    projectType: "Systems Integration / CRM",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2025-01",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Enabled behavioral profile data to be used within CRM systems for advisor workflows.",
    shortResumeVersion:
      "Enabled behavioral profile data to be used within CRM systems for advisor workflows.",
    longResumeVersion:
      "Defined workflow logic, data structure, and advisor use cases to make behavioral profile data actionable inside CRM environments.",
    context:
      "Investor personality data existed but was not embedded into advisors' daily workflows.",
    objective:
      "Make behavioral insights actionable inside CRM environments.",
    ownership: [
      "Workflow definition",
      "Data structuring logic",
      "Use-case design for advisors",
    ],
    deliverables: [
      "Structured export of behavioral profile data",
      "Connected internal CRM (Finliti Pulse) with advisor workflows",
      "Aligned personality data with advisor tools and decision-making",
    ],
    collaborators: ["CEO", "CTO", "Developer"],
    skills: [
      "Systems thinking",
      "CRM integration",
      "Data workflows",
      "Product implementation",
      "Stakeholder communication",
    ],
    tools: ["Finliti Pulse", "Behavioral profile data exports", "Advisor workflow systems"],
    outcomes: [
      "Enabled advisors to access client behavioral insights within workflow systems",
      "Increased usability of investor profile data",
    ],
    metrics: [
      { label: "Integration", value: "CRM workflows" },
      { label: "Data type", value: "Behavioral profiles" },
      { label: "Status", value: "Active" },
    ],
    tags: [
      "Systems Integration / CRM",
      "CRM integration",
      "Behavioral data",
      "Advisor workflows",
      "Data structure",
    ],
    featured: true,
    industry: "Fintech / WealthTech",
    audience: "Advisors",
    scopeLevel: "External / Integration",
    coverImage: {
      src: "/project-images/pm/crm-dashboard.png",
      alt: "Finliti client management dashboard used to represent CRM workflow integration.",
    },
    relatedProjects: [
      "advisor-dashboard-platform-expansion",
      "market-alerts-portfolio-signal-system",
    ],
  },
  {
    id: "market-alerts-portfolio-signal-system",
    slug: "market-alerts-portfolio-signal-system",
    title: "Market Alerts & Portfolio Signal System",
    shortTitle: "Market Alerts",
    category: "Project Management",
    projectType: "Product Feature / Alerts / Portfolio",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2025-01",
    timelineEnd: "Present",
    status: "Prototype",
    oneLineSummary:
      "Developed a system linking portfolio data and investor profiles to real-time market alerts.",
    shortResumeVersion:
      "Developed a system linking portfolio data and investor profiles to real-time market alerts.",
    longResumeVersion:
      "Owned the feature concept, workflow structure, and user value definition for a product layer that ties portfolios and investor profiles to ongoing alert logic.",
    context:
      "Product previously focused on static reports with limited ongoing value.",
    objective:
      "Create continuous value through real-time insights tied to portfolios and behavioral profiles.",
    ownership: [
      "Feature concept and structure",
      "Workflow clarity",
      "User value definition",
    ],
    deliverables: [
      "Portfolio asset shelf logic",
      "Alert system tied to user-defined assets",
      "Categorization of alerts based on investor profile",
      "Integration of signals into advisor workflow",
    ],
    collaborators: ["CEO", "CTO", "Developer"],
    skills: [
      "Product strategy",
      "Feature planning",
      "Workflow design",
      "Information architecture",
    ],
    tools: ["Portfolio data", "Market alerts", "Investor profile logic"],
    outcomes: [
      "Shifted product toward ongoing engagement vs one-time reports",
      "Added continuous advisor utility",
    ],
    metrics: [
      { label: "Value model", value: "Ongoing engagement" },
      { label: "Signal base", value: "Portfolio + profile" },
      { label: "Stage", value: "Prototype" },
    ],
    tags: [
      "Product Feature / Alerts / Portfolio",
      "Market alerts",
      "Portfolio workflow",
      "Feature planning",
      "Advisor utility",
    ],
    featured: false,
    industry: "Fintech / WealthTech",
    audience: "Advisors",
    scopeLevel: "External / Feature prototype",
    coverImage: {
      src: "/project-images/pm/market-alerts-dashboard.png",
      alt: "Finliti advisor platform screen used to represent portfolio and alerts work.",
    },
    relatedProjects: [
      "advisor-dashboard-platform-expansion",
      "crm-behavioral-profile-integration",
    ],
  },
  {
    id: "lifecycle-email-engagement-system",
    slug: "lifecycle-email-engagement-system",
    title: "Lifecycle Email & Engagement System",
    shortTitle: "Lifecycle Email",
    category: "Project Management",
    projectType: "Lifecycle / Communication / Engagement",
    company: "Finliti",
    role: "Content Lead to Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2021-01",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Built lifecycle email and newsletter system driving strong engagement and supporting onboarding.",
    shortResumeVersion:
      "Built lifecycle email and newsletter system driving strong engagement and supporting onboarding.",
    longResumeVersion:
      "Owned messaging strategy, content structure, and lifecycle communication flows across onboarding and ongoing engagement touchpoints.",
    context:
      "Users needed clearer communication and ongoing engagement touchpoints.",
    objective:
      "Improve user understanding, retention, and engagement.",
    ownership: [
      "Messaging strategy",
      "Content structure",
      "Lifecycle communication flows",
    ],
    deliverables: [
      "Lifecycle email sequences",
      "Weekly market newsletters",
      "Advisor-facing communications",
      "Structured communication tied to product journey",
    ],
    collaborators: ["CEO", "Product stakeholders"],
    skills: [
      "Lifecycle marketing",
      "Content strategy",
      "Communication design",
      "Onboarding support",
    ],
    tools: ["Email sequences", "Newsletters", "Product communication systems"],
    outcomes: [
      "Achieved ~42% open rate",
      "Improved ongoing user engagement",
    ],
    metrics: [
      { label: "Open rate", value: "~42%" },
      { label: "Cadence", value: "Weekly newsletters" },
      { label: "Focus", value: "Engagement + onboarding" },
    ],
    tags: [
      "Lifecycle / Communication / Engagement",
      "Email",
      "Newsletters",
      "Content strategy",
      "Retention",
    ],
    featured: false,
    industry: "Fintech / WealthTech",
    audience: "Advisors and product users",
    scopeLevel: "External / Communications",
    coverImage: {
      src: "/project-images/pm/lifecycle-newsletter.png",
      alt: "Finliti newsletter artwork representing lifecycle email and engagement work.",
    },
    relatedProjects: [
      "advisor-onboarding-system-transformation",
      "b2c-discovery-survey-funnel",
    ],
  },
  {
    id: "b2c-discovery-survey-funnel",
    slug: "b2c-discovery-survey-funnel",
    title: "B2C Discovery Survey Funnel",
    shortTitle: "Discovery Funnel",
    category: "Project Management",
    projectType: "Funnel / Product Experience",
    company: "Finliti",
    role: "Content Lead to Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2021-01",
    timelineEnd: "Present",
    status: "Launched",
    oneLineSummary:
      "Supported development of discovery survey funnel used by end users to generate behavioral profiles.",
    shortResumeVersion:
      "Supported development of discovery survey funnel used by end users to generate behavioral profiles.",
    longResumeVersion:
      "Owned survey experience, report framing, and messaging clarity for a scalable discovery funnel used to generate behavioral profiles.",
    context:
      "Finliti required a scalable entry point for new users.",
    objective:
      "Create an accessible and engaging user onboarding funnel.",
    ownership: [
      "Survey experience",
      "Report framing",
      "Messaging clarity",
    ],
    deliverables: [],
    collaborators: ["CEO", "Developer"],
    skills: [
      "User journey design",
      "Product messaging",
      "Funnel optimization",
    ],
    tools: ["Survey funnel", "Behavioral profile reports"],
    outcomes: ["1,000+ completed discovery surveys"],
    metrics: [
      { label: "Completions", value: "1,000+" },
      { label: "Channel", value: "B2C discovery" },
      { label: "State", value: "Active" },
    ],
    tags: [
      "Funnel / Product Experience",
      "Discovery survey",
      "User journey",
      "Behavioral profiles",
      "Funnel optimization",
    ],
    featured: false,
    industry: "Fintech / WealthTech",
    audience: "End users",
    scopeLevel: "External / B2C",
    coverImage: {
      src: "/project-images/pm/advisor-onboarding-flow.png",
      alt: "Finliti user journey flow representing the discovery survey funnel.",
      fit: "contain",
    },
    relatedProjects: ["lifecycle-email-engagement-system"],
  },
  {
    id: "enterprise-rollout-early-client-growth",
    slug: "enterprise-rollout-early-client-growth",
    title: "Enterprise Rollout & Early Client Growth",
    shortTitle: "Enterprise Rollout",
    category: "Project Management",
    projectType: "Product Rollout / Growth",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2023-01",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Helped transition Finliti from pre-revenue startup to a revenue-generating platform with advisor and enterprise clients.",
    shortResumeVersion:
      "Helped transition Finliti from pre-revenue startup to a revenue-generating platform with advisor and enterprise clients.",
    longResumeVersion:
      "Supported product readiness, onboarding, and client-facing execution as Finliti moved from an experimental stage to a commercial product with paying advisors and firms.",
    context:
      "Company was moving from experimental stage to commercial product.",
    objective:
      "Support product readiness and onboarding for paying clients.",
    ownership: [
      "Onboarding readiness",
      "Product presentation",
      "User experience clarity",
    ],
    deliverables: [],
    collaborators: ["CEO", "CTO", "Developer", "Advisors", "Firms"],
    skills: [
      "Product rollout",
      "Startup operations",
      "Client onboarding",
      "Implementation support",
    ],
    tools: ["Client onboarding workflows", "Product presentation", "Advisor delivery process"],
    outcomes: [
      "Growth from 0 clients to ~10 advisors plus multiple firms",
      "Supported early enterprise adoption",
    ],
    metrics: [
      { label: "Advisor growth", value: "~10 advisors" },
      { label: "Client base", value: "Multiple firms" },
      { label: "Stage shift", value: "Pre-revenue to active" },
    ],
    tags: [
      "Product Rollout / Growth",
      "Startup operations",
      "Client onboarding",
      "Enterprise adoption",
      "Implementation support",
    ],
    featured: true,
    industry: "Fintech / WealthTech",
    audience: "Advisors and enterprise firms",
    scopeLevel: "External / Enterprise / B2B",
    coverImage: {
      src: "/project-images/pm/rbc-finsec-deck.png",
      alt: "Finliti enterprise demo deck slide.",
    },
    relatedProjects: [
      "advisor-onboarding-system-transformation",
      "rbc-finsec-incubator-participation",
    ],
  },
  {
    id: "intern-coordination-feature-support",
    slug: "intern-coordination-feature-support",
    title: "Intern Coordination & Feature Support",
    shortTitle: "Intern Coordination",
    category: "Project Management",
    projectType: "Team Coordination",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2024-01",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Coordinated intern contributions across product features and ongoing development.",
    shortResumeVersion:
      "Coordinated intern contributions across product features and ongoing development.",
    longResumeVersion:
      "Managed task coordination, prioritization, and review across intern-supported product workstreams to keep evolving development aligned.",
    context:
      "Feature work required ongoing coordination and review across intern-supported product development.",
    objective:
      "Coordinate feature support and keep work aligned with current priorities.",
    ownership: [
      "Task coordination",
      "Work prioritization",
      "Review and alignment",
    ],
    deliverables: [],
    collaborators: ["Interns", "CEO", "CTO", "Developer"],
    skills: ["Coordination", "Prioritization", "Communication"],
    tools: ["Task coordination", "Async review", "Product feature support"],
    outcomes: [],
    metrics: [
      { label: "Work type", value: "Feature support" },
      { label: "Team model", value: "Intern coordination" },
      { label: "Status", value: "Ongoing" },
    ],
    tags: [
      "Team Coordination",
      "Prioritization",
      "Communication",
      "Feature support",
    ],
    featured: false,
    industry: "Fintech / WealthTech",
    audience: "Internal team",
    scopeLevel: "Internal",
    coverImage: {
      src: "/project-images/pm/advisor-onboarding-flow.png",
      alt: "Workflow diagram representing intern coordination and feature support.",
      fit: "contain",
    },
    relatedProjects: ["enterprise-rollout-early-client-growth"],
  },
  {
    id: "rbc-finsec-incubator-participation",
    slug: "rbc-finsec-incubator-participation",
    title: "RBC FinSec Incubator Participation",
    shortTitle: "RBC FinSec",
    category: "Project Management",
    projectType: "Stakeholder / Strategic",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2023-01",
    timelineEnd: "2023-12",
    status: "Strategic",
    oneLineSummary:
      "Participated in RBC FinSec incubator and engaged with fintech and banking stakeholders.",
    shortResumeVersion:
      "Participated in RBC FinSec incubator and engaged with fintech and banking stakeholders.",
    longResumeVersion:
      "Represented Finliti in the RBC FinSec incubator and contributed to product positioning and stakeholder conversations during an early growth stage.",
    context:
      "Finliti needed stronger positioning and stakeholder engagement while building credibility.",
    objective:
      "Support positioning, credibility, and industry engagement during early growth.",
    ownership: [
      "Stakeholder communication",
      "Product positioning",
      "Company representation",
    ],
    deliverables: [],
    collaborators: ["CEO", "Fintech stakeholders", "Banking stakeholders"],
    skills: [
      "Stakeholder communication",
      "Product positioning",
      "Fintech engagement",
    ],
    tools: ["Incubator participation", "Stakeholder meetings", "Product narrative"],
    outcomes: [
      "Contributed to positioning and industry engagement",
      "Supported credibility during early growth stage",
    ],
    metrics: [
      { label: "Program", value: "RBC FinSec" },
      { label: "Timeline", value: "2023" },
      { label: "Focus", value: "Stakeholder engagement" },
    ],
    tags: [
      "Stakeholder / Strategic",
      "Fintech",
      "Product positioning",
      "Industry engagement",
    ],
    featured: false,
    industry: "Fintech / Banking",
    audience: "Stakeholders and industry partners",
    scopeLevel: "External / Strategic",
    coverImage: {
      src: "/project-images/pm/rbc-finsec-deck.png",
      alt: "Finliti RBC FinSec presentation slide.",
    },
    relatedProjects: ["enterprise-rollout-early-client-growth"],
  },
  {
    id: "medsexpert-product-design-support",
    slug: "medsexpert-product-design-support",
    title: "medsEXPERT Product Design Support",
    shortTitle: "medsEXPERT",
    category: "Product / UX",
    projectType: "Product Design / UX",
    company: "medsEXPERT Pharmacy",
    role: "Product Designer",
    location: "Remote",
    timelineStart: "2022-08",
    timelineEnd: "2022-11",
    status: "Launched",
    oneLineSummary:
      "Contributed to product design and UX improvements for medsEXPERT Pharmacy.",
    shortResumeVersion:
      "Contributed to product design and UX improvements for medsEXPERT Pharmacy.",
    longResumeVersion:
      "Supported product design and UX improvement work for medsEXPERT Pharmacy, contributing to clearer user experiences and product-facing design decisions.",
    context:
      "The product needed focused UX and product design support to improve usability and overall user experience.",
    objective:
      "Contribute design and UX improvements that made the product clearer and easier to use.",
    ownership: [
      "Product design support",
      "UX improvement work",
      "User-facing design refinement",
    ],
    deliverables: [
      "Product UX improvements",
      "Interface refinement support",
      "Design contribution across active product work",
    ],
    collaborators: ["Product stakeholders", "Design collaborators"],
    skills: ["Product design", "UX design", "Interface refinement"],
    tools: ["Figma"],
    outcomes: [
      "Improved user-facing product experience",
      "Supported clearer UX direction",
    ],
    metrics: [
      { label: "Company", value: "medsEXPERT Pharmacy" },
      { label: "Timeline", value: "2022" },
      { label: "Focus", value: "Product UX" },
    ],
    tags: ["Product / UX", "Product design", "UX improvement"],
    featured: false,
    industry: "Healthcare / Pharmacy",
    audience: "Product users",
    scopeLevel: "External / Product",
  },
  {
    id: "purified-news-ux-research",
    slug: "purified-news-ux-research",
    title: "Purified News UX Research",
    shortTitle: "Purified News",
    category: "Product / UX",
    projectType: "UX Research / Product Direction",
    company: "Purified News",
    role: "UX Researcher",
    location: "Remote",
    timelineStart: "2021-09",
    timelineEnd: "2022-09",
    status: "Strategic",
    oneLineSummary:
      "Supported development of a Gen Z-focused news platform through UX research and product-direction work.",
    shortResumeVersion:
      "Supported development of a Gen Z-focused news platform through UX research and product-direction work.",
    longResumeVersion:
      "Conducted UX research and contributed to product direction for Purified News, supporting the development of a Gen Z-focused news platform.",
    context:
      "The platform needed stronger insight into user needs and product direction for a younger audience.",
    objective:
      "Support product direction with UX research grounded in audience behavior and needs.",
    ownership: [
      "UX research support",
      "Audience insight gathering",
      "Product-direction contribution",
    ],
    deliverables: [
      "UX research findings",
      "Audience-centered product input",
      "Research-backed product direction support",
    ],
    collaborators: ["Product team", "Editorial and design stakeholders"],
    skills: ["UX research", "Product strategy", "Audience insight"],
    tools: ["Research frameworks", "Product documentation"],
    outcomes: [
      "Supported development of a Gen Z-focused news product",
      "Helped shape product direction through research input",
    ],
    metrics: [
      { label: "Audience", value: "Gen Z" },
      { label: "Timeline", value: "2021–2022" },
      { label: "Focus", value: "UX research" },
    ],
    tags: ["Product / UX", "UX research", "Audience insight"],
    featured: false,
    industry: "Media / News",
    audience: "Gen Z readers",
    scopeLevel: "External / Product",
  },
  {
    id: "finliti-content-systems-explainers",
    slug: "finliti-content-systems-explainers",
    title: "Finliti Content Systems & Product Explainers",
    shortTitle: "Finliti Content",
    category: "Creative / Content",
    projectType: "Content Strategy / Product Messaging",
    company: "Finliti",
    role: "Content Lead / Content Developer",
    location: "Toronto, ON",
    timelineStart: "2021-10",
    timelineEnd: "2023-04",
    status: "Launched",
    oneLineSummary:
      "Developed investor reports, onboarding content, product explainers, and lifecycle messaging for a behavioral finance platform.",
    shortResumeVersion:
      "Developed investor reports, onboarding content, product explainers, and lifecycle messaging for Finliti.",
    longResumeVersion:
      "Created investor reports, onboarding content, product explainers, and lifecycle messaging that supported product clarity, brand voice, and platform development across Finliti's early growth stage.",
    context:
      "Finliti needed clearer product communication, stronger onboarding content, and a more consistent message system as the platform evolved.",
    objective:
      "Build content systems that made the product easier to understand and easier to adopt.",
    ownership: [
      "Investor report development",
      "Onboarding content",
      "Product explainers",
      "Lifecycle messaging",
    ],
    deliverables: [
      "Investor reports",
      "Onboarding copy and guidance",
      "Product explainer content",
      "Lifecycle messaging tied to investor personas",
    ],
    collaborators: ["CEO", "Product stakeholders", "Engineering collaborators"],
    skills: [
      "Content strategy",
      "Product messaging",
      "Lifecycle communication",
      "Narrative clarity",
    ],
    tools: ["Content systems", "Lifecycle messaging", "Product explainers"],
    outcomes: [
      "Improved product clarity for new and existing users",
      "Helped define brand voice across product touchpoints",
    ],
    metrics: [
      { label: "Timeline", value: "2021–2023" },
      { label: "Focus", value: "Content systems" },
      { label: "Company", value: "Finliti" },
    ],
    tags: [
      "Creative / Content",
      "Content strategy",
      "Product messaging",
      "Investor reports",
      "Lifecycle communication",
    ],
    featured: true,
    industry: "Fintech / WealthTech",
    audience: "Advisors and end users",
    scopeLevel: "External / Product communications",
    coverImage: {
      src: "/project-images/creative/finliti-content.png",
      alt: "Finliti newsletter artwork used to represent content systems and product explainers.",
    },
  },
  {
    id: "nimble-media-client-content-systems",
    slug: "nimble-media-client-content-systems",
    title: "Nimble Media Client Content Systems",
    shortTitle: "Nimble Media",
    category: "Creative / Content",
    projectType: "Content Strategy / Client Delivery",
    company: "Nimble Media",
    role: "Senior Copywriter",
    location: "Toronto, ON",
    timelineStart: "2020-03",
    timelineEnd: "2021-10",
    status: "Launched",
    oneLineSummary:
      "Produced branded content and messaging systems across 65+ client accounts.",
    shortResumeVersion:
      "Produced branded content and messaging systems across 65+ client accounts.",
    longResumeVersion:
      "Developed branded content, messaging frameworks, and email strategy work across 65+ clients while maintaining consistency across multiple platforms and delivery contexts.",
    context:
      "Clients required consistent messaging, content production, and campaign support across varied brand and channel needs.",
    objective:
      "Create strong messaging systems and brand-consistent content across multiple client accounts.",
    ownership: [
      "Branded content production",
      "Messaging frameworks",
      "Email marketing strategy",
      "Brand voice consistency",
    ],
    deliverables: [
      "Client campaigns",
      "Messaging frameworks",
      "Email strategy work",
      "Cross-platform branded content",
    ],
    collaborators: ["Clients", "Creative teams", "Marketing stakeholders"],
    skills: [
      "Content strategy",
      "Copywriting",
      "Messaging frameworks",
      "Email marketing",
    ],
    tools: ["Content systems", "Email strategy", "Campaign development"],
    outcomes: [
      "Produced work across 65+ clients",
      "Maintained consistent brand voice across multiple platforms",
    ],
    metrics: [
      { label: "Clients", value: "65+" },
      { label: "Timeline", value: "2020–2021" },
      { label: "Focus", value: "Content systems" },
    ],
    tags: ["Creative / Content", "Copywriting", "Client delivery", "Content strategy"],
    featured: false,
    industry: "Agency / Media",
    audience: "Client brands and campaign audiences",
    scopeLevel: "External / Client services",
    coverImage: {
      src: "/project-images/creative/finliti-content.png",
      alt: "Editorial-style artwork used as a stand-in cover for client content systems work.",
    },
  },
  {
    id: "scalepoynt-video-creative-lead",
    slug: "scalepoynt-video-creative-lead",
    title: "Scalepoynt Video & Creative Lead",
    shortTitle: "Scalepoynt",
    category: "Creative / Content",
    projectType: "Video / Creative Direction",
    company: "Scalepoynt",
    role: "Video Editor & Creative Lead",
    location: "Contract",
    timelineStart: "2023-01",
    timelineEnd: "2025-12",
    status: "Launched",
    oneLineSummary:
      "Edited promotional and educational videos and created motion-led product walkthrough visuals.",
    shortResumeVersion:
      "Edited promotional and educational videos and created motion-led product walkthrough visuals.",
    longResumeVersion:
      "Led video editing and creative production work for Scalepoynt, producing promotional and educational content alongside motion graphics and product walkthrough visuals.",
    context:
      "The brand needed polished video assets that could explain products clearly while supporting promotional goals.",
    objective:
      "Create clear, high-quality video assets for education, promotion, and product explanation.",
    ownership: [
      "Video editing",
      "Creative direction",
      "Motion graphics",
      "Product walkthrough visuals",
    ],
    deliverables: [
      "Promotional videos",
      "Educational content",
      "Motion graphics",
      "Product walkthrough visuals",
    ],
    collaborators: ["Client stakeholders", "Creative collaborators"],
    skills: [
      "Video editing",
      "Creative direction",
      "Motion design",
      "Visual storytelling",
    ],
    tools: ["Adobe Premiere Pro", "After Effects", "DaVinci Resolve"],
    outcomes: [
      "Produced educational and promotional video assets",
      "Improved visual clarity around product communication",
    ],
    metrics: [
      { label: "Timeline", value: "2023–2025" },
      { label: "Focus", value: "Video + motion" },
      { label: "Mode", value: "Contract" },
    ],
    tags: ["Creative / Content", "Video", "Motion graphics", "Creative lead"],
    featured: false,
    industry: "Creative / Commercial",
    audience: "Prospects, users, and stakeholders",
    scopeLevel: "External / Contract",
    coverImage: {
      src: "/project-images/creative/scalepoynt-badge.png",
      alt: "ScalePoynt brand badge.",
      fit: "contain",
    },
  },
  {
    id: "byeeee-feature-film",
    slug: "byeeee-feature-film",
    title: "Byeeee Feature Film",
    shortTitle: "Byeeee",
    category: "Film / Production",
    projectType: "Feature Film / Producing",
    company: "Independent Film",
    role: "Co-Producer",
    location: "Toronto, ON",
    timelineStart: "2024-01",
    timelineEnd: "2024-12",
    status: "Launched",
    oneLineSummary:
      "Served as co-producer on the feature film Byeeee, supporting production execution and delivery.",
    shortResumeVersion:
      "Co-produced the feature film Byeeee, supporting production execution and delivery.",
    longResumeVersion:
      "Worked as co-producer on Byeeee, contributing production support, coordination, and delivery discipline across a feature film environment.",
    context:
      "Feature production required cross-team coordination, schedule awareness, and execution discipline across a moving set of production needs.",
    objective:
      "Support smooth production execution and keep key production work moving toward delivery.",
    ownership: [
      "Co-producing support",
      "Production coordination",
      "Execution across active production needs",
    ],
    deliverables: [
      "Production coordination support",
      "Cross-team communication",
      "Delivery support across the feature timeline",
    ],
    collaborators: ["Director", "Producers", "Cast and crew"],
    skills: [
      "Producing",
      "Production coordination",
      "Scheduling",
      "Communication",
    ],
    tools: ["Production workflows", "Schedules", "Production communication"],
    outcomes: [
      "Supported feature production execution",
      "Strengthened delivery discipline in a film environment",
    ],
    metrics: [
      { label: "Format", value: "Feature film" },
      { label: "Year", value: "2024" },
      { label: "Role", value: "Co-Producer" },
    ],
    tags: ["Film / Production", "Feature film", "Producing", "Coordination"],
    featured: true,
    industry: "Film / Media",
    audience: "Production teams and audiences",
    scopeLevel: "External / Production",
  },
  {
    id: "get-hooked-production-coordination",
    slug: "get-hooked-production-coordination",
    title: "Get Hooked Production Coordination",
    shortTitle: "Get Hooked",
    category: "Film / Production",
    projectType: "TV / Assistant Directing",
    company: "OUTtv / Amazon",
    role: "2nd Assistant Director",
    location: "Toronto, ON",
    timelineStart: "2023-01",
    timelineEnd: "2023-12",
    status: "Launched",
    oneLineSummary:
      "Worked as 2nd Assistant Director on Get Hooked, supporting timing, communication, and on-set coordination.",
    shortResumeVersion:
      "Worked as 2nd Assistant Director on Get Hooked, supporting timing, communication, and on-set coordination.",
    longResumeVersion:
      "Supported production timing, communication, and on-set coordination as 2nd Assistant Director on Get Hooked for OUTtv / Amazon.",
    context:
      "TV production required precise coordination, clear communication, and quick response to shifting on-set needs.",
    objective:
      "Keep production moving cleanly through scheduling discipline and strong on-set coordination.",
    ownership: [
      "Assistant directing support",
      "On-set communication",
      "Schedule coordination",
    ],
    deliverables: [
      "Set coordination support",
      "Communication across departments",
      "Timing support for active production days",
    ],
    collaborators: ["Director", "Production team", "Cast and crew"],
    skills: [
      "Assistant directing",
      "Production coordination",
      "Scheduling",
      "On-set communication",
    ],
    tools: ["Call sheets", "Production schedules", "Set workflows"],
    outcomes: [
      "Supported organized, on-time production flow",
      "Built execution discipline in a high-variance TV environment",
    ],
    metrics: [
      { label: "Format", value: "TV" },
      { label: "Platform", value: "OUTtv / Amazon" },
      { label: "Role", value: "2nd AD" },
    ],
    tags: ["Film / Production", "TV", "Assistant directing", "Coordination"],
    featured: true,
    industry: "Television / Media",
    audience: "Production teams and audiences",
    scopeLevel: "External / Production",
  },
  {
    id: "finding-green-development",
    slug: "finding-green-development",
    title: "Finding Green Development",
    shortTitle: "Finding Green",
    category: "Film / Production",
    projectType: "Development / Writing",
    company: "Independent Development",
    role: "Creator / Writer",
    location: "Toronto, ON",
    timelineStart: "2023-01",
    timelineEnd: "Present",
    status: "Strategic",
    oneLineSummary:
      "Created and wrote Finding Green, a CMF/IPF-funded development project.",
    shortResumeVersion:
      "Created and wrote Finding Green, a CMF/IPF-funded development project.",
    longResumeVersion:
      "Led early creative development for Finding Green as creator and writer, shaping the concept, written material, and project direction through funded development.",
    context:
      "The project required early-stage creative definition, written development, and enough structure to move the concept forward through funding-backed development.",
    objective:
      "Build a clear creative foundation and advance the project through development.",
    ownership: [
      "Concept creation",
      "Writing",
      "Creative development",
      "Project direction",
    ],
    deliverables: [
      "Created the project concept",
      "Developed written material",
      "Supported funded development progress",
    ],
    collaborators: ["Development partners", "Creative collaborators"],
    skills: [
      "Writing",
      "Creative development",
      "Project direction",
      "Narrative design",
    ],
    tools: ["Development documents", "Writing workflows"],
    outcomes: [
      "Advanced the project through funded development",
      "Established a strong creative foundation for the work",
    ],
    metrics: [
      { label: "Format", value: "Development" },
      { label: "Funding", value: "CMF / IPF" },
      { label: "Role", value: "Creator / Writer" },
    ],
    tags: ["Film / Production", "Development", "Writing", "Creative direction"],
    featured: false,
    industry: "Film / TV Development",
    audience: "Development partners and future audiences",
    scopeLevel: "External / Development",
    coverImage: {
      src: "/project-images/film/finding-green.gif",
      alt: "Finding Green animated still.",
      fit: "cover",
    },
  },
  {
    id: "property-brothers-forever-home",
    slug: "property-brothers-forever-home",
    title: "Property Brothers: Forever Home",
    shortTitle: "Property Brothers",
    category: "Film / Production",
    projectType: "TV / Camera Department",
    company: "Property Brothers: Forever Home",
    role: "2nd Assistant Camera",
    location: "Toronto, ON",
    timelineStart: "2020-01",
    timelineEnd: "2020-12",
    status: "Launched",
    oneLineSummary:
      "Worked in the camera department as 2nd Assistant Camera on Property Brothers: Forever Home.",
    shortResumeVersion:
      "Worked in the camera department as 2nd Assistant Camera on Property Brothers: Forever Home.",
    longResumeVersion:
      "Supported camera department execution as 2nd Assistant Camera on Property Brothers: Forever Home, contributing to on-set coordination and technical production flow.",
    context:
      "Television production required organized technical support and smooth coordination within the camera department.",
    objective:
      "Support reliable camera department execution during active production.",
    ownership: [
      "Camera department support",
      "On-set technical coordination",
      "Production readiness",
    ],
    deliverables: [
      "Camera department support on production days",
      "Set readiness and technical coordination",
    ],
    collaborators: ["Camera department", "Directors", "Production crew"],
    skills: [
      "Camera support",
      "Production coordination",
      "Technical readiness",
      "On-set communication",
    ],
    tools: ["Camera workflows", "Production gear", "Set coordination"],
    outcomes: [
      "Supported smooth production execution in a TV environment",
      "Built technical and coordination discipline on set",
    ],
    metrics: [
      { label: "Format", value: "TV" },
      { label: "Department", value: "Camera" },
      { label: "Role", value: "2nd AC" },
    ],
    tags: ["Film / Production", "TV", "Camera department", "On-set support"],
    featured: false,
    industry: "Television / Media",
    audience: "Production teams and audiences",
    scopeLevel: "External / Production",
  },
  {
    id: "boy-in-bloom-short-film",
    slug: "boy-in-bloom-short-film",
    title: "Boy in Bloom",
    shortTitle: "Boy in Bloom",
    category: "Film / Production",
    projectType: "Short Film / Writing / Editing",
    company: "Independent Film",
    role: "Writer / Producer / Editor",
    location: "Toronto, ON",
    timelineStart: "2022-01",
    timelineEnd: "2022-12",
    status: "Launched",
    oneLineSummary:
      "Wrote, produced, and edited Boy in Bloom, a festival-selected short film.",
    shortResumeVersion:
      "Wrote, produced, and edited Boy in Bloom, a festival-selected short film.",
    longResumeVersion:
      "Led Boy in Bloom across writing, producing, and editing, carrying the project from creative development through a completed short film with festival selection.",
    context:
      "Independent short-form production required creative leadership alongside practical production and post-production execution.",
    objective:
      "Develop and deliver a strong short film through integrated creative and production leadership.",
    ownership: [
      "Writing",
      "Producing",
      "Editing",
      "End-to-end creative delivery",
    ],
    deliverables: [
      "Short film script and creative development",
      "Production execution",
      "Editorial completion",
    ],
    collaborators: ["Creative collaborators", "Cast and crew"],
    skills: [
      "Writing",
      "Producing",
      "Editing",
      "Creative direction",
    ],
    tools: ["Premiere Pro", "Production workflows", "Editorial systems"],
    outcomes: [
      "Delivered a completed short film",
      "Reached festival selection",
    ],
    metrics: [
      { label: "Format", value: "Short film" },
      { label: "Status", value: "Festival-selected" },
      { label: "Role", value: "Writer / Producer / Editor" },
    ],
    tags: ["Film / Production", "Short film", "Writing", "Editing", "Producing"],
    featured: true,
    industry: "Film / Media",
    audience: "Festival and film audiences",
    scopeLevel: "External / Production",
  },
  {
    id: "freelance-client-project-delivery",
    slug: "freelance-client-project-delivery",
    title: "Freelance Client Project Delivery",
    shortTitle: "Freelance Delivery",
    category: "Project Management",
    projectType: "Freelance / Client Delivery",
    company: "Freelance",
    role: "Project Lead / Creative Delivery",
    location: "Remote",
    timelineStart: "2020-01",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Managed digital and creative projects from concept through delivery for freelance clients and collaborators.",
    shortResumeVersion:
      "Managed digital and creative projects from concept through delivery for freelance clients and collaborators.",
    longResumeVersion:
      "Handled freelance and client-facing project work spanning concept development, delivery, documentation, collaborator coordination, and ongoing client relationship management.",
    context:
      "Freelance client work required both delivery execution and enough structure to keep projects moving cleanly across changing needs.",
    objective:
      "Manage creative and digital projects through delivery while maintaining client alignment and clear workflows.",
    ownership: [
      "Project management",
      "Workflow building",
      "Documentation",
      "Client relationship support",
    ],
    deliverables: [
      "Project delivery from concept through completion",
      "Client workflows and documentation",
      "Timeline and collaborator coordination",
    ],
    collaborators: ["Clients", "Creative collaborators"],
    skills: [
      "Project management",
      "Client communication",
      "Documentation",
      "Workflow design",
    ],
    tools: ["Documentation systems", "Client workflows"],
    outcomes: [
      "Maintained client relationships and project timelines",
      "Built workflows and documentation for collaborators and clients",
    ],
    metrics: [
      { label: "Mode", value: "Freelance" },
      { label: "Focus", value: "Client delivery" },
      { label: "Status", value: "Ongoing" },
    ],
    tags: ["Project Management", "Freelance", "Client delivery", "Documentation"],
    featured: false,
    industry: "Creative / Digital Services",
    audience: "Clients and collaborators",
    scopeLevel: "External / Client services",
    coverImage: {
      src: "/project-images/pm/advisor-onboarding-flow.png",
      alt: "Workflow diagram representing freelance client project delivery.",
      fit: "contain",
    },
  },
];
