import { Project } from "@/types/projects";

export const projects: Project[] = [
  {
    id: "advisor-onboarding-system-transformation",
    slug: "advisor-onboarding-system-transformation",
    title: "Advisor Onboarding System Transformation",
    shortTitle: "Pulse Launch",
    category: "Project Management",
    secondaryCategories: ["Product / UX"],
    projectType: "Onboarding / Implementation",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2023-03",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Moved advisor onboarding from a manual Typeform, Google Sheets, and database workflow into a self-serve Pulse platform flow with Stripe billing, survey setup, and in-platform client communication.",
    shortResumeVersion:
      "Redesigned advisor onboarding from a manual multi-step workflow into a self-serve platform experience that reduced setup from hours or days to minutes.",
    longResumeVersion:
      "Owned onboarding flow design, platform guidance, and system logic as Finliti moved advisor setup from a Typeform, Google Sheets, pgAdmin, and manual survey-link workflow into a centralized Pulse platform with Stripe plan selection, survey creation, activation controls, and in-platform client broadcast.",
    context:
      "Advisors were previously onboarded through a setup wizard and Typeform flow that fed Google Sheets. The team then manually created advisor records in pgAdmin, provisioned discovery surveys in Typeform, added clients one by one with unique identifiers, generated survey links manually, and handled payment outside the product.",
    objective:
      "Replace a manual, multi-person onboarding process with a faster, scalable advisor setup experience that handled billing, activation, survey setup, and communication inside one system.",
    ownership: [
      "Onboarding flow design",
      "User experience structure",
      "Activation logic and access states",
      "Survey setup and client broadcast workflow",
    ],
    deliverables: [
      "Designed advisor signup and plan-selection flow",
      "Implemented Stripe billing with 3 plan options",
      "Structured automated activation and feature-gating logic",
      "Created in-platform survey creation and preview workflow",
      "Built in-platform client broadcast and email workflow",
      "Introduced demo bypass and pilot-mode support",
    ],
    collaborators: ["CEO", "CTO", "1 software developer"],
    skills: [
      "Onboarding design",
      "Implementation",
      "Workflow design",
      "SaaS operations",
      "Stakeholder coordination",
      "Product operations",
    ],
    tools: ["Stripe", "Advisor dashboard", "Survey workflow"],
    outcomes: [
      "Onboarded ~10 active advisors across ~4 paid pilot firms",
      "Reduced onboarding from hours or days to minutes",
      "Eliminated 8+ manual onboarding and provisioning steps",
      "Enabled self-serve onboarding instead of assisted setup",
      "Improved scalability of advisor activation and pilot delivery",
    ],
    metrics: [
      { label: "Active advisors", value: "~10" },
      { label: "Paid pilot firms", value: "~4" },
      { label: "Time shift", value: "Days/hours to minutes" },
    ],
    tags: [
      "Onboarding / Implementation",
      "Advisor onboarding",
      "Stripe",
      "Workflow design",
      "Product operations",
    ],
    featured: true,
    industry: "Fintech / WealthTech",
    audience: "Advisors and advisory firms",
    scopeLevel: "External / B2B SaaS",
    coverImage: {
      src: "/project-images/pm/pulse-launch-diagram.svg",
      alt: "Animated onboarding diagram showing signup, Stripe, and activation flow.",
      fit: "cover",
      position: "center",
    },
    relatedProjects: [
      "advisor-dashboard-platform-expansion",
      "enterprise-rollout-early-client-growth",
    ],
  },
  {
    id: "advisor-dashboard-platform-expansion",
    slug: "advisor-dashboard-platform-expansion",
    title: "Advisor Dashboard & Platform Expansion",
    shortTitle: "Advisor Hub",
    category: "Project Management",
    secondaryCategories: ["Product / UX"],
    projectType: "Product Build / Dashboard / UX",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2023-03",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Expanded the product from a survey-and-report workflow into a unified advisor platform with dashboard, profile, backtesting, portfolio, alerts, newsletter, and AI surfaces.",
    shortResumeVersion:
      "Helped evolve the product from a simple survey/report tool into a multi-feature advisor platform with a centralized dashboard.",
    longResumeVersion:
      "Owned dashboard structure, product organization, and user-facing feature integration as Finliti evolved from a fragmented reporting workflow into a centralized advisor workspace with client profiles, backtesting, portfolio builder, market alerts, newsletter generation, and Pulse agent surfaces.",
    context:
      "Early product use centered on surveys and long reports, with limited in-platform workflow and no cohesive advisor operating system tying together onboarding, profiles, portfolio tools, alerts, and communications.",
    objective:
      "Create a cohesive advisor workspace where setup, client profiles, portfolio context, alerts, and communications live in one system.",
    ownership: [
      "Dashboard structure and logic",
      "Product organization and clarity",
      "User-facing feature integration",
      "Experience design",
    ],
    deliverables: [
      "Unified advisor dashboard",
      "Client profile visibility system",
      "Survey result integration",
      "Portfolio builder integration",
      "Backtesting tools integration",
      "Newsletter generator integration",
      "Pulse agent and voice-agent surfaces",
      "Structured feature navigation",
    ],
    collaborators: ["CEO", "CTO", "Software developer"],
    skills: [
      "UX design",
      "Product structuring",
      "Information architecture",
      "Feature integration",
      "Cross-functional collaboration",
    ],
    tools: [
      "Advisor dashboard",
      "Portfolio builder",
      "Backtesting tools",
      "Newsletter generator",
      "AI voice/audio agent",
    ],
    outcomes: [
      "Transformed product into a centralized SaaS platform",
      "Improved feature discoverability and product clarity",
      "Expanded the advisor experience beyond static reports",
      "Created a more usable ongoing workflow for advisors and firms",
    ],
    metrics: [
      { label: "Platform shift", value: "Report flow to advisor workspace" },
      { label: "Live modules", value: "7+ integrated surfaces" },
      { label: "Use model", value: "Centralized advisor dashboard" },
    ],
    tags: [
      "Product Build / Dashboard / UX",
      "Dashboard",
      "Information architecture",
      "Feature integration",
      "Advisor platform",
    ],
    featured: true,
    industry: "Fintech / WealthTech",
    audience: "Advisors",
    scopeLevel: "External / B2B SaaS",
    coverImage: {
      src: "/project-images/pm/Advisor-dashboard-home.png",
      alt: "Advisor workflow hub showing dashboard metrics, prioritized client work, and recent activity.",
      fit: "contain",
      position: "center top",
    },
    uiGallery: {
      desktop: [
        {
          src: "/project-images/pm/Advisor-dashboard-home.png",
          alt: "Advisor workflow hub showing dashboard metrics, prioritized client work, and recent activity.",
          caption: "Advisor home base for daily workflow, client follow-up, and activity tracking.",
          fit: "contain",
          position: "center top",
        },
        {
          src: "/project-images/pm/portfolio-builder-page.png",
          alt: "Portfolio builder screen mapping a client's goal to recommended asset allocation and backtest readiness.",
          caption: "Goal-based portfolio setup moved portfolio construction inside the platform.",
          fit: "contain",
          position: "center top",
        },
        {
          src: "/project-images/pm/backtest-results-page.png",
          alt: "Backtest results view comparing annual returns across a recommended portfolio and benchmarks.",
          caption: "Backtest analysis added evidence and comparison to the advisor workflow.",
          fit: "contain",
          position: "center top",
        },
      ],
    },
    relatedProjects: [
      "market-alerts-portfolio-signal-system",
      "crm-behavioral-profile-integration",
    ],
  },
  {
    id: "crm-behavioral-profile-integration",
    slug: "crm-behavioral-profile-integration",
    title: "CRM Behavioral Profile Integration",
    shortTitle: "Profile Sync",
    category: "Project Management",
    secondaryCategories: ["Product / UX"],
    projectType: "Systems Integration / CRM",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2025-01",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Defined how behavioral profile data should move into CRM and Pulse workflows so advisors could use client personality insights inside day-to-day practice.",
    shortResumeVersion:
      "Defined workflow logic for exporting behavioral profile data into CRM environments for advisor use.",
    longResumeVersion:
      "Defined workflow logic, data structure, and advisor use cases for moving behavioral profile data out of standalone reports and into CRM-connected workflows, including profile exports, internal Pulse connections, and advisor-facing action surfaces.",
    context:
      "Investor personality data existed, but it was not deeply embedded into advisor workflow systems. Advisors could access profile outputs, but the information was not yet structured for CRM-based use and follow-up.",
    objective:
      "Make profile data operational by connecting it to CRM and advisor workflow surfaces.",
    ownership: [
      "Workflow definition",
      "Data structuring logic",
      "Use-case design for advisors",
    ],
    deliverables: [
      "Structured export of behavioral profile data",
      "Defined internal Pulse workflow connections",
      "Aligned investor profile data with advisor tools and communications",
    ],
    collaborators: ["CEO", "CTO", "Developer"],
    skills: [
      "Systems thinking",
      "CRM integration",
      "Data workflows",
      "Product implementation",
      "Stakeholder communication",
    ],
    tools: ["Finliti Pulse", "Behavioral profile data exports", "Advisor workflow systems"],
    outcomes: [
      "Made personality-profile data more usable inside workflow systems",
      "Moved profile outputs closer to day-to-day advisor action",
    ],
    metrics: [
      { label: "Workflow surfaces", value: "CRM + Pulse" },
      { label: "Data type", value: "Behavioral profile exports" },
      { label: "Status", value: "Live and evolving" },
    ],
    tags: [
      "Systems Integration / CRM",
      "CRM integration",
      "Behavioral data",
      "Advisor workflows",
      "Data structure",
    ],
    featured: true,
    industry: "Fintech / WealthTech",
    audience: "Advisors",
    scopeLevel: "External / Integration",
    coverImage: {
      src: "/project-images/pm/CLIENT-DETAILS-PAGE.png",
      alt: "Client profile overview showing behavioral trait scores, survey status, and profile summary inside the advisor platform.",
      fit: "contain",
      position: "center top",
    },
    uiGallery: {
      desktop: [
        {
          src: "/project-images/pm/CLIENT-DETAILS-PAGE.png",
          alt: "Client profile overview showing behavioral trait scores, survey status, and profile summary inside the advisor platform.",
          caption: "Behavioral profile data became usable inside a live client record.",
          fit: "contain",
          position: "center top",
        },
        {
          src: "/project-images/pm/Advisor-dashboard-home.png",
          alt: "Advisor workflow hub with recent client activity and tasks connected to profile review.",
          caption: "Profile work fed into the daily advisor queue and client follow-up flow.",
          fit: "contain",
          position: "center top",
        },
        {
          src: "/project-images/pm/market-alerts-page.png",
          alt: "Market alerts screen showing client-selected assets and recommended tickers tied to the current client.",
          caption: "Client context could carry forward into downstream alert and recommendation surfaces.",
          fit: "contain",
          position: "center top",
        },
      ],
    },
    relatedProjects: [
      "advisor-dashboard-platform-expansion",
      "market-alerts-portfolio-signal-system",
    ],
  },
  {
    id: "market-alerts-portfolio-signal-system",
    slug: "market-alerts-portfolio-signal-system",
    title: "Market Alerts & Portfolio Signal System",
    shortTitle: "Signal Layer",
    category: "Project Management",
    secondaryCategories: ["Product / UX"],
    projectType: "Product Feature / Alerts / Portfolio",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2025-01",
    timelineEnd: "Present",
    status: "Prototype",
    oneLineSummary:
      "Helped structure a market-alert workflow connecting CSV asset shelves, portfolio data, and investor profile logic into ongoing advisor signals.",
    shortResumeVersion:
      "Helped structure a market-alert workflow connecting portfolio data and investor profile logic into ongoing advisor signals.",
    longResumeVersion:
      "Owned the feature concept, workflow structure, and user value definition for a product layer where firms can upload product shelves via CSV, map assets into categories, and generate profile-aware market alerts and advisor-facing signals.",
    context:
      "Product previously focused on static reports with limited ongoing value.",
    objective:
      "Create ongoing advisor utility through profile-aware alerts tied to client portfolios and firm product shelves.",
    ownership: [
      "Feature concept and structure",
      "Workflow clarity",
      "User value definition",
    ],
    deliverables: [
      "Portfolio shelf upload logic",
      "Alert system tied to uploaded assets and tickers",
      "Risk and profile-based signal categorization",
      "Advisor-facing structure for alerts and insights",
    ],
    collaborators: ["CEO", "CTO", "Developer"],
    skills: [
      "Product strategy",
      "Feature planning",
      "Workflow design",
      "Information architecture",
    ],
    tools: ["Portfolio data", "Market alerts", "Investor profile logic"],
    outcomes: [
      "Shifted product toward ongoing engagement vs one-time reports",
      "Added continuous advisor utility",
      "Connected uploaded portfolio shelves to profile-aware alert logic",
    ],
    metrics: [
      { label: "Input model", value: "CSV portfolio shelves" },
      { label: "Signal base", value: "Portfolio + profile logic" },
      { label: "Stage", value: "Prototype / live workflow" },
    ],
    tags: [
      "Product Feature / Alerts / Portfolio",
      "Market alerts",
      "Portfolio workflow",
      "Feature planning",
      "Advisor utility",
    ],
    featured: false,
    industry: "Fintech / WealthTech",
    audience: "Advisors",
    scopeLevel: "External / Feature prototype",
    coverImage: {
      src: "/project-images/pm/market-alerts-page.png",
      alt: "Market alerts screen showing tracked assets, client context, and generated updates inside the advisor platform.",
      fit: "contain",
      position: "center top",
    },
    uiGallery: {
      desktop: [
        {
          src: "/project-images/pm/market-alerts-page.png",
          alt: "Market alerts screen showing tracked assets, client context, and generated updates inside the advisor platform.",
          caption: "Market alerts translated selected assets and client context into an ongoing signal layer.",
          fit: "contain",
          position: "center top",
        },
        {
          src: "/project-images/pm/portfolio-builder-page.png",
          alt: "Portfolio builder screen where an advisor sets client goals and recommended allocation before alerts are generated.",
          caption: "Portfolio setup created the asset mix that downstream alerts would monitor.",
          fit: "contain",
          position: "center top",
        },
        {
          src: "/project-images/pm/backtest-results-page.png",
          alt: "Backtest results page showing performance analysis and allocation comparisons tied to the alert workflow.",
          caption: "Backtest results gave the alerts system a performance context and rationale layer.",
          fit: "contain",
          position: "center top",
        },
      ],
    },
    relatedProjects: [
      "advisor-dashboard-platform-expansion",
      "crm-behavioral-profile-integration",
    ],
  },
  {
    id: "lifecycle-email-engagement-system",
    slug: "lifecycle-email-engagement-system",
    title: "Lifecycle Email & Engagement System",
    shortTitle: "Message Engine",
    category: "Project Management",
    projectType: "Lifecycle / Communication / Engagement",
    company: "Finliti",
    role: "Content Lead to Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2021-01",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Built lifecycle email and newsletter systems supporting onboarding, retention, and profile-tailored client communication across the platform.",
    shortResumeVersion:
      "Built lifecycle email and newsletter systems supporting onboarding and retention, including communications with roughly 42% open rates.",
    longResumeVersion:
      "Owned messaging strategy, content structure, and lifecycle communication flows across onboarding and ongoing engagement touchpoints, including weekly newsletters, profile-aware communication cadence, and advisor-facing content systems built into the platform.",
    context:
      "Users needed clearer communication and ongoing engagement touchpoints.",
    objective:
      "Improve user understanding, retention, and engagement.",
    ownership: [
      "Messaging strategy",
      "Content structure",
      "Lifecycle communication flows",
    ],
    deliverables: [
      "Lifecycle email sequences",
      "Weekly market newsletters",
      "Advisor-facing communications",
      "Automated communication cadence tied to profile type and product journey",
    ],
    collaborators: ["CEO", "Product stakeholders"],
    skills: [
      "Lifecycle marketing",
      "Content strategy",
      "Communication design",
      "Onboarding support",
    ],
    tools: ["Email sequences", "Newsletters", "Product communication systems"],
    outcomes: [
      "Achieved ~42% open rate",
      "Improved ongoing user engagement",
      "Extended product communication beyond onboarding into recurring touchpoints",
    ],
    metrics: [
      { label: "Open rate", value: "~42%" },
      { label: "Cadence", value: "Weekly newsletters" },
      { label: "System", value: "Lifecycle + newsletter engine" },
    ],
    tags: [
      "Lifecycle / Communication / Engagement",
      "Email",
      "Newsletters",
      "Content strategy",
      "Retention",
    ],
    featured: false,
    industry: "Fintech / WealthTech",
    audience: "Advisors and product users",
    scopeLevel: "External / Communications",
    coverImage: {
      src: "/project-images/pm/message-engine-diagram.svg",
      alt: "Animated email cadence diagram showing welcome, nurture, and weekly message flow.",
    },
    relatedProjects: [
      "advisor-onboarding-system-transformation",
      "b2c-discovery-survey-funnel",
    ],
  },
  {
    id: "b2c-discovery-survey-funnel",
    slug: "b2c-discovery-survey-funnel",
    title: "B2C Discovery Survey Funnel",
    shortTitle: "Discovery Flow",
    category: "Project Management",
    secondaryCategories: ["Product / UX"],
    projectType: "Funnel / Product Experience",
    company: "Finliti",
    role: "Content Lead to Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2021-01",
    timelineEnd: "Present",
    status: "Launched",
    oneLineSummary:
      "Supported the early B2C discovery funnel, MyFinliti beta, and Finlitiverse education concept used to generate behavioral profiles and test consumer-facing product direction.",
    shortResumeVersion:
      "Supported the B2C discovery survey funnel and MyFinliti beta experience used to generate behavioral profiles at scale.",
    longResumeVersion:
      "Owned survey experience, report framing, and messaging clarity for Finliti's early B2C funnel, including the MyFinliti beta and Finlitiverse concept direction, before the company shifted more heavily toward the B2B advisor platform.",
    context:
      "Finliti initially tested a more consumer-facing entry point through MyFinliti and Finlitiverse concepts before prioritizing the B2B advisor platform.",
    objective:
      "Create an accessible and engaging user onboarding funnel.",
    ownership: [
      "Survey experience",
      "Report framing",
      "Messaging clarity",
    ],
    deliverables: [],
    collaborators: ["CEO", "Developer"],
    skills: [
      "User journey design",
      "Product messaging",
      "Funnel optimization",
    ],
    tools: ["Survey funnel", "Behavioral profile reports"],
    outcomes: ["1,000+ completed discovery surveys"],
    metrics: [
      { label: "Completions", value: "1,000+" },
      { label: "Beta users", value: "~500" },
      { label: "Channel", value: "B2C discovery funnel" },
    ],
    tags: [
      "Funnel / Product Experience",
      "Discovery survey",
      "User journey",
      "Behavioral profiles",
      "Funnel optimization",
    ],
    featured: false,
    industry: "Fintech / WealthTech",
    audience: "End users",
    scopeLevel: "External / B2C",
    coverImage: {
      src: "/project-images/pm/discovery-flow-diagram.svg",
      alt: "Animated user flow diagram showing survey, profile reveal, and report path.",
      fit: "cover",
    },
    relatedProjects: ["lifecycle-email-engagement-system"],
  },
  {
    id: "enterprise-rollout-early-client-growth",
    slug: "enterprise-rollout-early-client-growth",
    title: "Enterprise Rollout & Early Client Growth",
    shortTitle: "Growth Ops",
    category: "Project Management",
    projectType: "Product Rollout / Growth",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2023-01",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Helped move Finliti from pre-revenue startup operations to a more structured B2B platform with paid pilots, firm onboarding, and enterprise-ready workflows.",
    shortResumeVersion:
      "Helped transition Finliti from pre-revenue startup operations to a more structured B2B platform with advisor and firm adoption.",
    longResumeVersion:
      "Supported product readiness, onboarding, and client-facing execution as Finliti moved from experimental B2C and pilot workflows to a more commercial B2B platform with advisor onboarding, annual plan structure, enterprise conversations, and more repeatable delivery systems.",
    context:
      "The company was shifting from pre-seed experimentation and manual pilot delivery toward a more productized B2B platform with paying advisors, firm relationships, and enterprise-facing requirements.",
    objective:
      "Support product readiness, client onboarding, and delivery systems that could hold up for paying advisors and firms.",
    ownership: [
      "Onboarding readiness",
      "Product presentation",
      "User experience clarity",
    ],
    deliverables: [],
    collaborators: ["CEO", "CTO", "Developer", "Advisors", "Firms"],
    skills: [
      "Product rollout",
      "Startup operations",
      "Client onboarding",
      "Implementation support",
    ],
    tools: ["Client onboarding workflows", "Product presentation", "Advisor delivery process"],
    outcomes: [
      "Supported growth from 0 clients/revenue to ~10 advisors across ~4 firms",
      "Helped turn manual pilot delivery into a more scalable platform model",
      "Supported paid pilot delivery through monthly and annual plan structure",
      "Supported early enterprise and annual-plan readiness",
    ],
    metrics: [
      { label: "Active advisors", value: "~10" },
      { label: "Paid pilot firms", value: "~4" },
      { label: "Pricing", value: "$300/mo or $3,000/yr" },
    ],
    tags: [
      "Product Rollout / Growth",
      "Startup operations",
      "Client onboarding",
      "Enterprise adoption",
      "Implementation support",
    ],
    featured: true,
    industry: "Fintech / WealthTech",
    audience: "Advisors and enterprise firms",
    scopeLevel: "External / Enterprise / B2B",
    coverImage: {
      src: "/project-images/pm/growth-ops-diagram.svg",
      alt: "Animated growth diagram showing movement from zero clients to paid pilot firms.",
    },
    relatedProjects: [
      "advisor-onboarding-system-transformation",
      "rbc-finsec-incubator-participation",
    ],
  },
  {
    id: "intern-coordination-feature-support",
    slug: "intern-coordination-feature-support",
    title: "Intern Coordination & Feature Support",
    shortTitle: "Team Flow",
    category: "Project Management",
    projectType: "Team Coordination",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2024-01",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Coordinated 1-2 interns across product features and ongoing development while aligning work with a small startup delivery team.",
    shortResumeVersion:
      "Coordinated intern contributions across product features and ongoing development.",
    longResumeVersion:
      "Managed task coordination, prioritization, and review across 1-2 intern-supported workstreams while aligning delivery with the CEO, CTO, and developer.",
    context:
      "Feature work required ongoing coordination and review across intern-supported product development.",
    objective:
      "Coordinate feature support and keep work aligned with current priorities.",
    ownership: [
      "Task coordination",
      "Work prioritization",
      "Review and alignment",
    ],
    deliverables: [],
    collaborators: ["Interns", "CEO", "CTO", "Developer"],
    skills: ["Coordination", "Prioritization", "Communication"],
    tools: ["Task coordination", "Async review", "Product feature support"],
    outcomes: [],
    metrics: [
      { label: "Interns", value: "1-2" },
      { label: "Core team", value: "CEO, CTO, developer" },
      { label: "Focus", value: "Feature support + coordination" },
    ],
    tags: [
      "Team Coordination",
      "Prioritization",
      "Communication",
      "Feature support",
    ],
    featured: false,
    industry: "Fintech / WealthTech",
    audience: "Internal team",
    scopeLevel: "Internal",
    coverImage: {
      src: "/project-images/pm/team-flow-diagram.svg",
      alt: "Animated team coordination diagram showing startup stakeholders and interns in one workflow.",
      fit: "cover",
    },
    relatedProjects: ["enterprise-rollout-early-client-growth"],
  },
  {
    id: "rbc-finsec-incubator-participation",
    slug: "rbc-finsec-incubator-participation",
    title: "RBC FinSec Incubator Participation",
    shortTitle: "FinSec Track",
    category: "Project Management",
    projectType: "Stakeholder / Strategic",
    company: "Finliti",
    role: "Product & Content Lead",
    location: "Toronto, ON",
    timelineStart: "2023-01",
    timelineEnd: "2023-12",
    status: "Strategic",
    oneLineSummary:
      "Represented Finliti in the RBC FinSec incubator and engaged with fintech and banking stakeholders during early growth.",
    shortResumeVersion:
      "Participated in RBC FinSec incubator and engaged with fintech and banking stakeholders.",
    longResumeVersion:
      "Represented Finliti in the RBC FinSec incubator and contributed to product positioning and stakeholder conversations during an early growth stage.",
    context:
      "Finliti needed stronger positioning and stakeholder engagement while building credibility.",
    objective:
      "Support positioning, credibility, and industry engagement during early growth.",
    ownership: [
      "Stakeholder communication",
      "Product positioning",
      "Company representation",
    ],
    deliverables: [],
    collaborators: ["CEO", "Fintech stakeholders", "Banking stakeholders"],
    skills: [
      "Stakeholder communication",
      "Product positioning",
      "Fintech engagement",
    ],
    tools: ["Incubator participation", "Stakeholder meetings", "Product narrative"],
    outcomes: [
      "Contributed to positioning and industry engagement",
      "Supported credibility during early growth stage",
    ],
    metrics: [
      { label: "Program", value: "1 RBC FinSec cohort" },
      { label: "Timeline", value: "2023" },
      { label: "Focus", value: "Stakeholder engagement" },
    ],
    tags: [
      "Stakeholder / Strategic",
      "Fintech",
      "Product positioning",
      "Industry engagement",
    ],
    featured: false,
    industry: "Fintech / Banking",
    audience: "Stakeholders and industry partners",
    scopeLevel: "External / Strategic",
    coverImage: {
      src: "/project-images/pm/finsec-track-diagram.svg",
      alt: "Animated stakeholder diagram showing RBC, banks, and fintech connections.",
    },
    relatedProjects: ["enterprise-rollout-early-client-growth"],
  },
  {
    id: "medsexpert-product-design-support",
    slug: "medsexpert-product-design-support",
    title: "medsEXPERT Product Design Support",
    shortTitle: "medsEXPERT",
    category: "Product / UX",
    projectType: "Product Design / UX",
    company: "medsEXPERT Pharmacy",
    role: "Product Designer",
    location: "Remote",
    timelineStart: "2022-08",
    timelineEnd: "2022-11",
    status: "Launched",
    oneLineSummary:
      "Contributed to product design and UX improvement work for medsEXPERT Pharmacy, helping clarify user-facing flows in a healthcare context.",
    shortResumeVersion:
      "Contributed to product design and UX improvements for medsEXPERT Pharmacy.",
    longResumeVersion:
      "Supported product design and UX improvement work for medsEXPERT Pharmacy, contributing to clearer user experiences and product-facing design decisions.",
    context:
      "The product needed focused UX and product design support to improve usability and overall user experience.",
    objective:
      "Contribute design and UX improvements that made the product clearer and easier to use.",
    ownership: [
      "Product design support",
      "UX improvement work",
      "User-facing design refinement",
    ],
    deliverables: [
      "Product UX improvements",
      "Interface refinement support",
      "Design contribution across active product work",
    ],
    collaborators: ["Product stakeholders", "Design collaborators"],
    skills: ["Product design", "UX design", "Interface refinement"],
    tools: ["Figma"],
    outcomes: [
      "Improved user-facing product experience",
      "Supported clearer UX direction",
    ],
    metrics: [
      { label: "Industry", value: "Healthcare / Pharmacy" },
      { label: "Timeline", value: "Aug-Nov 2022" },
      { label: "Focus", value: "Product UX improvement" },
    ],
    tags: ["Product / UX", "Product design", "UX improvement"],
    featured: false,
    industry: "Healthcare / Pharmacy",
    audience: "Product users",
    scopeLevel: "External / Product",
  },
  {
    id: "purified-news-ux-research",
    slug: "purified-news-ux-research",
    title: "Purified News UX Research",
    shortTitle: "Purified News",
    category: "Product / UX",
    projectType: "UX Research / Product Direction",
    company: "Purified News",
    role: "UX Researcher",
    location: "Remote",
    timelineStart: "2021-09",
    timelineEnd: "2022-09",
    status: "Strategic",
    oneLineSummary:
      "Supported development of a Gen Z-focused news platform through UX research, audience insight work, and product-direction support.",
    shortResumeVersion:
      "Supported development of a Gen Z-focused news platform through UX research and product-direction work.",
    longResumeVersion:
      "Conducted UX research and contributed to product direction for Purified News, supporting the development of a Gen Z-focused news platform.",
    context:
      "The platform needed stronger insight into user needs and product direction for a younger audience.",
    objective:
      "Support product direction with UX research grounded in audience behavior and needs.",
    ownership: [
      "UX research support",
      "Audience insight gathering",
      "Product-direction contribution",
    ],
    deliverables: [
      "UX research findings",
      "Audience-centered product input",
      "Research-backed product direction support",
    ],
    collaborators: ["Product team", "Editorial and design stakeholders"],
    skills: ["UX research", "Product strategy", "Audience insight"],
    tools: ["Research frameworks", "Product documentation"],
    outcomes: [
      "Supported development of a Gen Z-focused news product",
      "Helped shape product direction through research input",
    ],
    metrics: [
      { label: "Audience", value: "Gen Z" },
      { label: "Timeline", value: "2021-2022" },
      { label: "Focus", value: "UX research + product direction" },
    ],
    tags: ["Product / UX", "UX research", "Audience insight"],
    featured: false,
    industry: "Media / News",
    audience: "Gen Z readers",
    scopeLevel: "External / Product",
  },
  {
    id: "finliti-content-systems-explainers",
    slug: "finliti-content-systems-explainers",
    title: "Finliti Content Systems & Product Explainers",
    shortTitle: "Finliti Content",
    category: "Creative / Content",
    projectType: "Content Strategy / Product Messaging",
    company: "Finliti",
    role: "Content Lead / Content Developer",
    location: "Toronto, ON",
    timelineStart: "2021-10",
    timelineEnd: "2023-04",
    status: "Launched",
    oneLineSummary:
      "Developed investor reports, onboarding content, product explainers, and lifecycle messaging that made a behavioral finance platform easier to understand and use.",
    shortResumeVersion:
      "Developed investor reports, onboarding content, product explainers, and lifecycle messaging for Finliti.",
    longResumeVersion:
      "Created investor reports, onboarding content, product explainers, and lifecycle messaging that supported product clarity, brand voice, and platform development across Finliti's early growth stage.",
    context:
      "Finliti needed clearer product communication, stronger onboarding content, and a more consistent message system as the platform evolved.",
    objective:
      "Build content systems that made the product easier to understand and easier to adopt.",
    ownership: [
      "Investor report development",
      "Onboarding content",
      "Product explainers",
      "Lifecycle messaging",
    ],
    deliverables: [
      "Investor reports",
      "Onboarding copy and guidance",
      "Product explainer content",
      "Lifecycle messaging tied to investor personas",
    ],
    collaborators: ["CEO", "Product stakeholders", "Engineering collaborators"],
    skills: [
      "Content strategy",
      "Product messaging",
      "Lifecycle communication",
      "Narrative clarity",
    ],
    tools: ["Content systems", "Lifecycle messaging", "Product explainers"],
    outcomes: [
      "Improved product clarity for new and existing users",
      "Helped define brand voice across product touchpoints",
      "Built content systems spanning reports, onboarding, and lifecycle flows",
    ],
    metrics: [
      { label: "Coverage", value: "Reports, onboarding, lifecycle" },
      { label: "Timeline", value: "2021-2023" },
      { label: "Company", value: "Finliti" },
    ],
    tags: [
      "Creative / Content",
      "Content strategy",
      "Product messaging",
      "Investor reports",
      "Lifecycle communication",
    ],
    featured: true,
    industry: "Fintech / WealthTech",
    audience: "Advisors and end users",
    scopeLevel: "External / Product communications",
    coverImage: {
      src: "/project-images/creative/finliti-content.png",
      alt: "Finliti newsletter artwork used to represent content systems and product explainers.",
    },
  },
  {
    id: "nimble-media-client-content-systems",
    slug: "nimble-media-client-content-systems",
    title: "Nimble Media Client Content Systems",
    shortTitle: "Nimble Media",
    category: "Creative / Content",
    projectType: "Content Strategy / Client Delivery",
    company: "Nimble Media",
    role: "Senior Copywriter",
    location: "Toronto, ON",
    timelineStart: "2020-03",
    timelineEnd: "2021-10",
    status: "Launched",
    oneLineSummary:
      "Produced branded content and messaging systems across 65+ client accounts.",
    shortResumeVersion:
      "Produced branded content and messaging systems across 65+ client accounts.",
    longResumeVersion:
      "Developed branded content, messaging frameworks, and email strategy work across 65+ clients while maintaining consistency across multiple platforms and delivery contexts.",
    context:
      "Clients required consistent messaging, content production, and campaign support across varied brand and channel needs.",
    objective:
      "Create strong messaging systems and brand-consistent content across multiple client accounts.",
    ownership: [
      "Branded content production",
      "Messaging frameworks",
      "Email marketing strategy",
      "Brand voice consistency",
    ],
    deliverables: [
      "Client campaigns",
      "Messaging frameworks",
      "Email strategy work",
      "Cross-platform branded content",
    ],
    collaborators: ["Clients", "Creative teams", "Marketing stakeholders"],
    skills: [
      "Content strategy",
      "Copywriting",
      "Messaging frameworks",
      "Email marketing",
    ],
    tools: ["Content systems", "Email strategy", "Campaign development"],
    outcomes: [
      "Produced work across 65+ clients",
      "Maintained consistent brand voice across multiple platforms",
    ],
    metrics: [
      { label: "Clients", value: "65+" },
      { label: "Timeline", value: "2020–2021" },
      { label: "Focus", value: "Content systems" },
    ],
    tags: ["Creative / Content", "Copywriting", "Client delivery", "Content strategy"],
    featured: false,
    industry: "Agency / Media",
    audience: "Client brands and campaign audiences",
    scopeLevel: "External / Client services",
    coverImage: {
      src: "/project-images/creative/finliti-content.png",
      alt: "Editorial-style artwork used as a stand-in cover for client content systems work.",
    },
  },
  {
    id: "scalepoynt-video-creative-lead",
    slug: "scalepoynt-video-creative-lead",
    title: "Scalepoynt Video & Creative Lead",
    shortTitle: "Scalepoynt",
    category: "Creative / Content",
    projectType: "Video / Creative Direction",
    company: "Scalepoynt",
    role: "Video Editor & Creative Lead",
    location: "Contract",
    timelineStart: "2023-01",
    timelineEnd: "2025-12",
    status: "Launched",
    oneLineSummary:
      "Edited 20+ promotional and educational videos and created motion-led product walkthrough visuals for a multi-year client engagement.",
    shortResumeVersion:
      "Edited promotional and educational videos and created motion-led product walkthrough visuals.",
    longResumeVersion:
      "Led video editing and creative production work for Scalepoynt, producing promotional and educational content alongside motion graphics and product walkthrough visuals.",
    context:
      "The brand needed polished video assets that could explain products clearly while supporting promotional goals.",
    objective:
      "Create clear, high-quality video assets for education, promotion, and product explanation.",
    ownership: [
      "Video editing",
      "Creative direction",
      "Motion graphics",
      "Product walkthrough visuals",
    ],
    deliverables: [
      "Promotional videos",
      "Educational content",
      "Motion graphics",
      "Product walkthrough visuals",
    ],
    collaborators: ["Client stakeholders", "Creative collaborators"],
    skills: [
      "Video editing",
      "Creative direction",
      "Motion design",
      "Visual storytelling",
    ],
    tools: ["Adobe Premiere Pro", "After Effects", "DaVinci Resolve"],
    outcomes: [
      "Produced educational and promotional video assets",
      "Improved visual clarity around product communication",
    ],
    metrics: [
      { label: "Videos", value: "20+" },
      { label: "Timeline", value: "2023-2025" },
      { label: "Focus", value: "Video, motion, walkthroughs" },
      { label: "Mode", value: "Contract engagement" },
    ],
    tags: ["Creative / Content", "Video", "Motion graphics", "Creative lead"],
    featured: false,
    industry: "Creative / Commercial",
    audience: "Prospects, users, and stakeholders",
    scopeLevel: "External / Contract",
    coverVideo: {
      src: "https://www.youtube.com/watch?v=SnujwfivhBc&t=2s",
      title: "ScalePoynt cover reel",
    },
  },
  {
    id: "byeeee-feature-film",
    slug: "byeeee-feature-film",
    title: "Byeeee Feature Film",
    shortTitle: "Byeeee",
    category: "Film / Production",
    projectType: "Feature Film / Producing",
    company: "Think/Feel",
    role: "Co-Producer",
    location: "Toronto, ON",
    timelineStart: "2024-01",
    timelineEnd: "2024-12",
    status: "Launched",
    oneLineSummary:
      "Served as co-producer on the feature film Byeeee, supporting production execution, coordination, and delivery across a full feature timeline.",
    shortResumeVersion:
      "Co-produced the feature film Byeeee, supporting production execution and delivery.",
    longResumeVersion:
      "Worked as co-producer on Byeeee, contributing production support, coordination, and delivery discipline across a feature film environment.",
    context:
      "Feature production required cross-team coordination, schedule awareness, and execution discipline across a moving set of production needs.",
    objective:
      "Support smooth production execution and keep key production work moving toward delivery.",
    ownership: [
      "Co-producing support",
      "Production coordination",
      "Execution across active production needs",
    ],
    deliverables: [
      "Production coordination support",
      "Cross-team communication",
      "Delivery support across the feature timeline",
    ],
    collaborators: ["Director", "Producers", "Cast and crew"],
    skills: [
      "Producing",
      "Production coordination",
      "Scheduling",
      "Communication",
    ],
    tools: ["Production workflows", "Schedules", "Production communication"],
    outcomes: [
      "Supported feature production execution",
      "Strengthened delivery discipline in a film environment",
    ],
    metrics: [
      { label: "Format", value: "1 feature film" },
      { label: "Year", value: "2024" },
      { label: "Role", value: "Co-Producer" },
    ],
    tags: ["Film / Production", "Feature film", "Producing", "Coordination"],
    featured: true,
    industry: "Film / Media",
    audience: "Production teams and audiences",
    scopeLevel: "External / Production",
    coverImage: {
      src: "/project-images/film/byeeee-billboard.png",
      alt: "Byeeee billboard artwork over a tree canopy.",
      fit: "cover",
    },
    galleryImages: [
      {
        src: "/project-images/film/byeeee-poster.png",
        alt: "Byeeee poster artwork.",
        fit: "cover",
        position: "center top",
      },
      {
        src: "/project-images/film/byeeee-billboard.png",
        alt: "Byeeee billboard artwork over a tree canopy.",
        fit: "cover",
      },
    ],
  },
  {
    id: "get-hooked-production-coordination",
    slug: "get-hooked-production-coordination",
    title: "Get Hooked Production Coordination",
    shortTitle: "Get Hooked",
    category: "Film / Production",
    projectType: "TV / Assistant Directing",
    company: "OUTtv / Amazon",
    role: "2nd Assistant Director",
    location: "Toronto, ON",
    timelineStart: "2023-01",
    timelineEnd: "2023-12",
    status: "Launched",
    oneLineSummary:
      "Worked as 2nd Assistant Director on Get Hooked, supporting call sheets, timing, talent movement, and on-set coordination for an OUTtv / Amazon docuseries.",
    shortResumeVersion:
      "Worked as 2nd Assistant Director on Get Hooked, supporting timing, communication, and on-set coordination.",
    longResumeVersion:
      "Supported production timing, call sheets, communication, and on-set coordination as 2nd Assistant Director on Get Hooked, a queer fishing docuseries for OUTtv / Amazon.",
    context:
      "TV production required precise coordination, clear communication, and quick response to shifting on-set needs.",
    objective:
      "Keep production moving cleanly through scheduling discipline and strong on-set coordination.",
    ownership: [
      "Assistant directing support",
      "On-set communication",
      "Schedule coordination",
    ],
    deliverables: [
      "Call-sheet execution",
      "Set coordination support",
      "Communication across departments",
      "Timing and talent support for active production days",
    ],
    collaborators: ["Director", "Production team", "Cast and crew"],
    skills: [
      "Assistant directing",
      "Production coordination",
      "Scheduling",
      "On-set communication",
    ],
    tools: ["Call sheets", "Production schedules", "Set workflows"],
    outcomes: [
      "Supported organized, on-time production flow",
      "Built execution discipline in a high-variance TV environment",
    ],
    metrics: [
      { label: "Format", value: "TV series" },
      { label: "Platform", value: "OUTtv / Amazon" },
      { label: "Role", value: "2nd AD" },
    ],
    tags: ["Film / Production", "TV", "Assistant directing", "Coordination"],
    featured: true,
    industry: "Television / Media",
    audience: "Production teams and audiences",
    scopeLevel: "External / Production",
    coverImage: {
      src: "/project-images/film/gethooked-billboard.jpg",
      alt: "Get Hooked billboard artwork.",
      fit: "cover",
    },
    galleryImages: [
      {
        src: "/project-images/film/gethooked-billboard.jpg",
        alt: "Get Hooked billboard artwork.",
        fit: "cover",
      },
      {
        src: "/project-images/film/gethooked-poster.png",
        alt: "Get Hooked poster artwork.",
        fit: "cover",
      },
    ],
  },
  {
    id: "finding-green-development",
    slug: "finding-green-development",
    title: "Finding Green Development",
    shortTitle: "Finding Green",
    category: "Film / Production",
    projectType: "Development / Writing",
    company: "Bone Vault Inc.",
    role: "Creator / Writer",
    location: "Toronto, ON",
    timelineStart: "2023-01",
    timelineEnd: "Present",
    status: "Strategic",
    oneLineSummary:
      "Created and wrote Finding Green, an optioned CMF/IPF-funded development project that reached early streaming-partner discussions.",
    shortResumeVersion:
      "Created and wrote Finding Green, a CMF/IPF-funded development project.",
    longResumeVersion:
      "Led early creative development for Finding Green as creator and writer, shaping the concept, scripts, and pitch materials; secured CMF/IPF development support and advanced into early discussions with KindaTV (Shaftesbury).",
    context:
      "The project required early-stage creative definition, written development, and enough structure to move the concept forward through funding-backed development.",
    objective:
      "Build a clear creative foundation and advance the project through development.",
    ownership: [
      "Concept creation",
      "Writing",
      "Creative development",
      "Project direction",
    ],
    deliverables: [
      "Created the project concept",
      "Developed scripts and pitch materials",
      "Supported funded development progress",
    ],
    collaborators: ["Development partners", "Creative collaborators"],
    skills: [
      "Writing",
      "Creative development",
      "Project direction",
      "Narrative design",
    ],
    tools: ["Development documents", "Writing workflows"],
    outcomes: [
      "Advanced the project through funded development",
      "Reached early deal discussion with KindaTV (Shaftesbury)",
    ],
    metrics: [
      { label: "Format", value: "TV / web-series development" },
      { label: "Funding", value: "CMF / IPF" },
      { label: "Status", value: "Optioned project" },
    ],
    tags: ["Film / Production", "Development", "Writing", "Creative direction"],
    featured: false,
    industry: "Film / TV Development",
    audience: "Development partners and future audiences",
    scopeLevel: "External / Development",
    coverVideo: {
      src: "https://www.youtube.com/watch?v=8UY056BMFb4&t=6s",
      title: "Finding Green development trailer",
    },
  },
  {
    id: "property-brothers-forever-home",
    slug: "property-brothers-forever-home",
    title: "Property Brothers: Forever Home",
    shortTitle: "Property Brothers",
    category: "Film / Production",
    projectType: "TV / Camera Department",
    company: "Property Brothers: Forever Home",
    role: "2nd Assistant Camera",
    location: "Toronto, ON",
    timelineStart: "2020-01",
    timelineEnd: "2020-12",
    status: "Launched",
    oneLineSummary:
      "Worked in the camera department as 2nd Assistant Camera on Property Brothers: Forever Home, supporting technical readiness and on-set flow.",
    shortResumeVersion:
      "Worked in the camera department as 2nd Assistant Camera on Property Brothers: Forever Home.",
    longResumeVersion:
      "Supported camera department execution as 2nd Assistant Camera on Property Brothers: Forever Home, contributing to on-set coordination and technical production flow.",
    context:
      "Television production required organized technical support and smooth coordination within the camera department.",
    objective:
      "Support reliable camera department execution during active production.",
    ownership: [
      "Camera department support",
      "On-set technical coordination",
      "Production readiness",
    ],
    deliverables: [
      "Camera department support on production days",
      "Set readiness and technical coordination",
    ],
    collaborators: ["Camera department", "Directors", "Production crew"],
    skills: [
      "Camera support",
      "Production coordination",
      "Technical readiness",
      "On-set communication",
    ],
    tools: ["Camera workflows", "Production gear", "Set coordination"],
    outcomes: [
      "Supported smooth production execution in a TV environment",
      "Built technical and coordination discipline on set",
    ],
    metrics: [
      { label: "Format", value: "TV series" },
      { label: "Department", value: "Camera" },
      { label: "Role", value: "2nd AC" },
    ],
    tags: ["Film / Production", "TV", "Camera department", "On-set support"],
    featured: false,
    industry: "Television / Media",
    audience: "Production teams and audiences",
    scopeLevel: "External / Production",
    links: [
      {
        label: "Watch on HGTV",
        href: "https://watch.hgtv.com/video/2294932",
      },
      {
        label: "View on IMDb",
        href: "https://www.imdb.com/title/tt9855018/",
      },
    ],
  },
  {
    id: "boy-in-bloom-short-film",
    slug: "boy-in-bloom-short-film",
    title: "Boy in Bloom",
    shortTitle: "Boy in Bloom",
    category: "Film / Production",
    projectType: "Short Film / Writing / Editing",
    company: "Independent Film",
    role: "Writer / Producer / Editor",
    location: "Toronto, ON",
    timelineStart: "2022-01",
    timelineEnd: "2022-12",
    status: "Launched",
    oneLineSummary:
      "Wrote, produced, and edited Boy in Bloom, a festival-selected short film.",
    shortResumeVersion:
      "Wrote, produced, and edited Boy in Bloom, a festival-selected short film.",
    longResumeVersion:
      "Led Boy in Bloom across writing, producing, and editing, carrying the project from creative development through a completed short film with festival selection.",
    context:
      "Independent short-form production required creative leadership alongside practical production and post-production execution.",
    objective:
      "Develop and deliver a strong short film through integrated creative and production leadership.",
    ownership: [
      "Writing",
      "Producing",
      "Editing",
      "End-to-end creative delivery",
    ],
    deliverables: [
      "Short film script and creative development",
      "Production execution",
      "Editorial completion",
    ],
    collaborators: ["Creative collaborators", "Cast and crew"],
    skills: [
      "Writing",
      "Producing",
      "Editing",
      "Creative direction",
    ],
    tools: ["Premiere Pro", "Production workflows", "Editorial systems"],
    outcomes: [
      "Delivered a completed short film",
      "Reached festival selection",
      "Screened at TIFF, KCFF, and Canada Shorts",
    ],
    metrics: [
      { label: "Format", value: "Short film" },
      { label: "Festivals", value: "TIFF, KCFF, Canada Shorts" },
      { label: "Status", value: "Award-winning / festival-selected" },
    ],
    tags: ["Film / Production", "Short film", "Writing", "Editing", "Producing"],
    featured: true,
    industry: "Film / Media",
    audience: "Festival and film audiences",
    scopeLevel: "External / Production",
    coverVideo: {
      src: "https://www.youtube.com/watch?v=Z2mB-0BCS0g",
      title: "Boy In Bloom | A Short Film",
    },
    links: [
      {
        label: "Watch on YouTube",
        href: "https://www.youtube.com/watch?v=Z2mB-0BCS0g",
      },
      {
        label: "View on IMDb",
        href: "https://www.imdb.com/title/tt11826624/",
      },
    ],
  },
  {
    id: "freelance-client-project-delivery",
    slug: "freelance-client-project-delivery",
    title: "Freelance Client Project Delivery",
    shortTitle: "Client Ops",
    category: "Project Management",
    projectType: "Freelance / Client Delivery",
    company: "Freelance",
    role: "Project Lead / Creative Delivery",
    location: "Remote",
    timelineStart: "2020-01",
    timelineEnd: "Present",
    status: "Ongoing",
    oneLineSummary:
      "Managed digital and creative projects from concept through delivery for freelance clients, collaborators, and ongoing creative work.",
    shortResumeVersion:
      "Managed digital and creative projects from concept through delivery for freelance clients and collaborators.",
    longResumeVersion:
      "Handled freelance and client-facing project work spanning concept development, delivery, documentation, collaborator coordination, and ongoing client relationship management.",
    context:
      "Freelance client work required both delivery execution and enough structure to keep projects moving cleanly across changing needs.",
    objective:
      "Manage creative and digital projects through delivery while maintaining client alignment and clear workflows.",
    ownership: [
      "Project management",
      "Workflow building",
      "Documentation",
      "Client relationship support",
    ],
    deliverables: [
      "Project delivery from concept through completion",
      "Client workflows and documentation",
      "Timeline and collaborator coordination",
    ],
    collaborators: ["Clients", "Creative collaborators"],
    skills: [
      "Project management",
      "Client communication",
      "Documentation",
      "Workflow design",
    ],
    tools: ["Documentation systems", "Client workflows"],
    outcomes: [
      "Maintained client relationships and project timelines",
      "Built workflows and documentation for collaborators and clients",
    ],
    metrics: [
      { label: "Mode", value: "Freelance" },
      { label: "Focus", value: "Client delivery + documentation" },
      { label: "Status", value: "Ongoing" },
    ],
    tags: ["Project Management", "Freelance", "Client delivery", "Documentation"],
    featured: false,
    industry: "Creative / Digital Services",
    audience: "Clients and collaborators",
    scopeLevel: "External / Client services",
    coverImage: {
      src: "/project-images/pm/client-ops-diagram.svg",
      alt: "Animated client delivery diagram showing brief, build, and handoff workflow.",
      fit: "cover",
    },
  },
  {
    id: "next-ai-cohort",
    slug: "next-ai-cohort",
    title: "Next AI Cohort",
    shortTitle: "Next AI",
    category: "Product / UX",
    projectType: "AI / Product Strategy",
    company: "Next AI",
    role: "Cohort Participant",
    location: "Toronto, ON",
    timelineStart: "2023-03",
    timelineEnd: "2023-09",
    status: "Strategic",
    oneLineSummary:
      "Participated in the Next AI '23 cohort, expanding exposure to AI product thinking, startup strategy, and founder-facing technical conversations.",
    shortResumeVersion:
      "Participated in the Next AI '23 cohort, strengthening AI product and startup strategy exposure.",
    longResumeVersion:
      "Participated in the Next AI 2023 cohort, building exposure to AI product strategy, startup thinking, and technical founder/operator conversations alongside Finliti's product growth stage.",
    context:
      "The cohort provided a structured environment for AI product exposure, startup conversations, and adjacent founder/operator learning.",
    objective:
      "Deepen understanding of AI product strategy and early-stage venture ecosystems.",
    ownership: [
      "Cohort participation",
      "AI product exploration",
      "Startup ecosystem exposure",
    ],
    deliverables: [
      "Cohort participation",
      "AI/startup learning",
      "Founder-facing product discussion",
    ],
    collaborators: ["Cohort members", "Mentors", "Startup operators"],
    skills: ["AI product strategy", "Startup ecosystems", "Product thinking"],
    tools: ["Cohort workshops", "AI product discussions"],
    outcomes: ["Expanded AI product and startup strategy exposure"],
    metrics: [
      { label: "Program", value: "Next AI '23" },
      { label: "Timeline", value: "2023" },
      { label: "Focus", value: "AI + startup strategy" },
    ],
    tags: ["Product / UX", "AI", "Startup strategy", "Cohort"],
    featured: false,
    industry: "AI / Startups",
    audience: "Founders and product operators",
    scopeLevel: "External / Cohort",
  },
  {
    id: "gold-link-documentary-research",
    slug: "gold-link-documentary-research",
    title: "Gold Link Documentary Research",
    shortTitle: "Gold Link",
    category: "Creative / Content",
    projectType: "Research / Story Development",
    company: "Gold Link Productions Inc.",
    role: "Research Assistant",
    location: "Toronto, ON",
    timelineStart: "2018-04",
    timelineEnd: "2018-10",
    status: "Launched",
    oneLineSummary:
      "Supported documentary story development through structured research and editorial preparation.",
    shortResumeVersion:
      "Supported documentary story development and research for Gold Link Productions.",
    longResumeVersion:
      "Worked as a research assistant supporting documentary story development, source gathering, and early editorial preparation work.",
    context:
      "Documentary development required research discipline and organized support for story shaping.",
    objective:
      "Support documentary development with accurate research and useful source material.",
    ownership: ["Research support", "Story development assistance", "Source gathering"],
    deliverables: ["Documentary research", "Story support materials", "Research organization"],
    collaborators: ["Producers", "Story team"],
    skills: ["Research", "Story development", "Editorial support"],
    tools: ["Research workflows", "Documentation"],
    outcomes: ["Supported stronger documentary development groundwork"],
    metrics: [
      { label: "Format", value: "Documentary development" },
      { label: "Timeline", value: "2018" },
      { label: "Role", value: "Research Assistant" },
    ],
    tags: ["Creative / Content", "Research", "Story development", "Documentary"],
    featured: false,
    industry: "Documentary / Media",
    audience: "Production and editorial teams",
    scopeLevel: "External / Research",
  },
  {
    id: "toronto-urban-growers-urban-ag-week",
    slug: "toronto-urban-growers-urban-ag-week",
    title: "Toronto Urban Growers Storytelling",
    shortTitle: "TUG Urban Ag Week",
    category: "Creative / Content",
    projectType: "Video / Community Storytelling",
    company: "Toronto Urban Growers",
    role: "Director / Editor",
    location: "Toronto, ON",
    timelineStart: "2021-09",
    timelineEnd: "2021-09",
    status: "Launched",
    oneLineSummary:
      "Created a short community-storytelling video for Thorncliffe Park Urban Farmers as part of TUG Urban Ag Week 2021.",
    shortResumeVersion:
      "Created a short community-storytelling video for Thorncliffe Park Urban Farmers during TUG Urban Ag Week 2021.",
    longResumeVersion:
      "Produced a short-form community storytelling piece focused on Thorncliffe Park Urban Farmers for Toronto Urban Growers' Urban Ag Week 2021 programming.",
    context:
      "The work needed to spotlight community-led urban agriculture in a concise, accessible format tied to a public-facing event context.",
    objective:
      "Create a clear, human-centered video piece that could support community visibility and event storytelling.",
    ownership: ["Direction", "Editing", "Story shaping"],
    deliverables: ["Short-form video", "Community-storytelling edit", "Event-facing media asset"],
    collaborators: ["Toronto Urban Growers", "Thorncliffe Park Urban Farmers"],
    skills: ["Video editing", "Storytelling", "Community-focused content"],
    tools: ["Video production", "Editing workflows"],
    outcomes: ["Delivered a published Urban Ag Week 2021 video asset"],
    metrics: [
      { label: "Program", value: "Urban Ag Week 2021" },
      { label: "Format", value: "Community video" },
      { label: "Org", value: "Toronto Urban Growers" },
    ],
    tags: ["Creative / Content", "Video", "Community storytelling", "Toronto Urban Growers"],
    featured: false,
    industry: "Community / Nonprofit / Media",
    audience: "Public audiences and community stakeholders",
    scopeLevel: "External / Community storytelling",
    coverVideo: {
      src: "https://vimeo.com/593368341?fl=pl&fe=cm",
      title: "Thorncliffe Park Urban Farmers - Drawdown Toronto - TUG Urban Ag Week 2021",
    },
  },
  {
    id: "royal-lepage-executive-assistant",
    slug: "royal-lepage-executive-assistant",
    title: "Royal LePage Executive Support",
    shortTitle: "Royal LePage",
    category: "Project Management",
    projectType: "Operations / Executive Support",
    company: "Royal LePage Partners Realty",
    role: "Executive Assistant",
    location: "Kingston, ON",
    timelineStart: "2014-08",
    timelineEnd: "2015-08",
    status: "Launched",
    oneLineSummary:
      "Supported executive operations, scheduling, and administrative coordination in a real-estate brokerage environment.",
    shortResumeVersion:
      "Provided executive support and operations coordination for a busy real-estate brokerage office.",
    longResumeVersion:
      "Worked in executive support and office coordination, handling scheduling, communication, and administrative workflow in a client-facing real-estate setting.",
    context:
      "The role required dependable coordination, communication, and administrative follow-through in a high-touch service business.",
    objective:
      "Keep executive and office operations moving smoothly through organized support.",
    ownership: ["Executive support", "Scheduling", "Administrative coordination"],
    deliverables: ["Scheduling support", "Office coordination", "Administrative workflow management"],
    collaborators: ["Executives", "Office staff", "Clients"],
    skills: ["Operations", "Scheduling", "Administrative support", "Communication"],
    tools: ["Office workflows", "Scheduling systems"],
    outcomes: ["Supported consistent office and executive operations"],
    metrics: [
      { label: "Industry", value: "Real estate" },
      { label: "Timeline", value: "2014-2015" },
      { label: "Role", value: "Executive Assistant" },
    ],
    tags: ["Project Management", "Operations", "Executive support", "Scheduling"],
    featured: false,
    industry: "Real Estate / Operations",
    audience: "Executives, office staff, clients",
    scopeLevel: "Internal / Operations",
    coverImage: {
      src: "/project-images/pm/client-ops-diagram.svg",
      alt: "Animated workflow diagram representing operations and executive support.",
      fit: "cover",
    },
  },
];
